import { Series } from '../src/types';

export const CLASSIC_MOVIES_DATABASE: Series[] = [
  // ==========================================
  // PRE-70s (1960s & EARLIER)
  // ==========================================
  {
    id: 'the-good-the-bad-and-the-ugly',
    imdbId: 'tt0060196',
    mediaType: 'movie',
    title: 'The Good, the Bad and the Ugly',
    tagline: 'For three men the Civil War wasn\'t about peace. It was about $200,000.',
    synopsis: 'A bounty hunting scam joins two men in an uneasy alliance against a third in a race to find a fortune in gold buried in a remote cemetery.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/4/45/Good_the_bad_and_the_ugly_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/4/45/Good_the_bad_and_the_ugly_poster.jpg',
    providers: ['max', 'prime'],
    primaryProvider: 'max',
    genres: ['Western', 'Adventure'],
    rating: 8.8,
    ratingCount: '810K+',
    contentRating: 'R',
    firstAirYear: 1966,
    decade: 'Pre-70s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 178,
    director: 'Sergio Leone',
    network: 'United Artists / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Clint Eastwood Western Masterpiece',
    cast: [
      { name: 'Clint Eastwood', role: 'Blondie (The Good / The Man with No Name)' },
      { name: 'Lee Van Cleef', role: 'Angel Eyes (The Bad)' },
      { name: 'Eli Wallach', role: 'Tuco (The Ugly)' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1966-12-23',
        status: 'released',
      },
    ],
  },
  {
    id: 'a-fistful-of-dollars',
    imdbId: 'tt0058461',
    mediaType: 'movie',
    title: 'A Fistful of Dollars',
    tagline: 'In his own way he is perhaps, the most dangerous man who ever lived!',
    synopsis: 'A wandering gunfighter plays two rival families against each other in a town torn apart by greed, pride, and vengeance.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ed/A_Fistful_of_Dollars_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/e/ed/A_Fistful_of_Dollars_poster.jpg',
    providers: ['max', 'prime'],
    primaryProvider: 'max',
    genres: ['Western', 'Action', 'Drama'],
    rating: 7.9,
    ratingCount: '240K+',
    contentRating: 'R',
    firstAirYear: 1964,
    decade: 'Pre-70s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 99,
    director: 'Sergio Leone',
    network: 'United Artists / Prime Video',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'First of the Dollars Trilogy',
    cast: [
      { name: 'Clint Eastwood', role: 'The Man with No Name' },
      { name: 'Gian Maria Volonté', role: 'Ramón Rojo' },
      { name: 'Marianne Koch', role: 'Marisol' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1964-09-12',
        status: 'released',
      },
    ],
  },
  {
    id: 'for-a-few-dollars-more',
    imdbId: 'tt0059578',
    mediaType: 'movie',
    title: 'For a Few Dollars More',
    tagline: 'The man with no name is back... the man in black is waiting... and the bounty is high!',
    synopsis: 'Two bounty hunters with the same intentions team up to track down a ruthless outlaw and his gang of cutthroats.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/5/52/For_a_few_dollars_more.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/5/52/For_a_few_dollars_more.jpg',
    providers: ['max', 'prime'],
    primaryProvider: 'max',
    genres: ['Western', 'Action'],
    rating: 8.2,
    ratingCount: '280K+',
    contentRating: 'R',
    firstAirYear: 1965,
    decade: 'Pre-70s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 132,
    director: 'Sergio Leone',
    network: 'United Artists / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Sergio Leone Western Legend',
    cast: [
      { name: 'Clint Eastwood', role: 'Monco / The Man with No Name' },
      { name: 'Lee Van Cleef', role: 'Col. Douglas Mortimer' },
      { name: 'Gian Maria Volonté', role: 'El Indio' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1965-12-18',
        status: 'released',
      },
    ],
  },
  {
    id: 'casablanca',
    imdbId: 'tt0034583',
    mediaType: 'movie',
    title: 'Casablanca',
    tagline: 'They had a date with fate in Casablanca!',
    synopsis: 'A cynical American expatriate struggles to decide whether or not he should help his former lover and her fugitive husband escape French Morocco.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/CasablancaPoster-Gold.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/CasablancaPoster-Gold.jpg',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Drama', 'Romance', 'War'],
    rating: 8.5,
    ratingCount: '600K+',
    contentRating: 'PG',
    firstAirYear: 1942,
    decade: 'Pre-70s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 102,
    director: 'Michael Curtiz',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Cinema Golden Age Legend',
    cast: [
      { name: 'Humphrey Bogart', role: 'Rick Blaine' },
      { name: 'Ingrid Bergman', role: 'Ilsa Lund' },
      { name: 'Paul Henreid', role: 'Victor Laszlo' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1942-11-26',
        status: 'released',
      },
    ],
  },
  {
    id: '12-angry-men',
    imdbId: 'tt0050083',
    mediaType: 'movie',
    title: '12 Angry Men',
    tagline: 'Life is in their hands. Death is on their minds.',
    synopsis: 'The jury in a New York City murder trial is frustrated by a single member whose skeptical caution forces them to more carefully consider the evidence before jumping to a hasty verdict.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/12_Angry_Men_%281957_film_poster%29.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/12_Angry_Men_%281957_film_poster%29.jpg',
    providers: ['prime', 'mubi'],
    primaryProvider: 'prime',
    genres: ['Crime', 'Drama'],
    rating: 9.0,
    ratingCount: '870K+',
    contentRating: 'Not Rated',
    firstAirYear: 1957,
    decade: 'Pre-70s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 96,
    director: 'Sidney Lumet',
    network: 'United Artists / Prime',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Top 5 Highest Rated Film on IMDb',
    cast: [
      { name: 'Henry Fonda', role: 'Juror 8' },
      { name: 'Lee J. Cobb', role: 'Juror 3' },
      { name: 'Martin Balsam', role: 'Juror 1' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1957-04-10',
        status: 'released',
      },
    ],
  },
  {
    id: 'psycho-1960',
    imdbId: 'tt0054215',
    mediaType: 'movie',
    title: 'Psycho',
    tagline: 'The picture you MUST see from the beginning... Or not at all!',
    synopsis: 'A Phoenix secretary embezzles $40,000 from her employer\'s client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/76/Psycho_%281960%29_theatrical_poster_%28retouched%29.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/76/Psycho_%281960%29_theatrical_poster_%28retouched%29.jpg',
    providers: ['peacock'],
    primaryProvider: 'peacock',
    genres: ['Horror', 'Mystery', 'Thriller'],
    rating: 8.5,
    ratingCount: '720K+',
    contentRating: 'R',
    firstAirYear: 1960,
    decade: 'Pre-70s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 109,
    director: 'Alfred Hitchcock',
    network: 'Paramount / Universal',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Alfred Hitchcock Masterpiece',
    cast: [
      { name: 'Anthony Perkins', role: 'Norman Bates' },
      { name: 'Janet Leigh', role: 'Marion Crane' },
      { name: 'Vera Miles', role: 'Lila Crane' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1960-09-08',
        status: 'released',
      },
    ],
  },
  {
    id: '2001-a-space-odyssey',
    imdbId: 'tt0062622',
    mediaType: 'movie',
    title: '2001: A Space Odyssey',
    tagline: 'An epic drama of adventure and exploration.',
    synopsis: 'After uncovering a mysterious artifact buried beneath the Lunar surface, a spacecraft is sent to Jupiter to find its origins, accompanied by two men and the supercomputer H.A.L. 9000.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/1/11/2001_A_Space_Odyssey_%281968%29_theatrical_poster_variant.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/1/11/2001_A_Space_Odyssey_%281968%29_theatrical_poster_variant.jpg',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Sci-Fi', 'Adventure'],
    rating: 8.3,
    ratingCount: '730K+',
    contentRating: 'G',
    firstAirYear: 1968,
    decade: 'Pre-70s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 149,
    director: 'Stanley Kubrick',
    network: 'MGM / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Stanley Kubrick Sci-Fi Landmark',
    cast: [
      { name: 'Keir Dullea', role: 'Dr. David Bowman' },
      { name: 'Gary Lockwood', role: 'Dr. Frank Poole' },
      { name: 'Douglas Rain', role: 'HAL 9000 (voice)' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1968-04-03',
        status: 'released',
      },
    ],
  },

  // ==========================================
  // 1970s
  // ==========================================
  {
    id: 'dirty-harry',
    imdbId: 'tt0066999',
    mediaType: 'movie',
    title: 'Dirty Harry',
    tagline: 'You don\'t assign him to murder cases. You turn him loose.',
    synopsis: 'When a madman dubbed \'Scorpio\' terrorizes San Francisco, hard-nosed police inspector Harry Callahan is assigned to track down the psychopath by any means necessary.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6f/Dirty_harry.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6f/Dirty_harry.jpg',
    providers: ['max', 'prime'],
    primaryProvider: 'max',
    genres: ['Action', 'Crime', 'Thriller'],
    rating: 7.7,
    ratingCount: '170K+',
    contentRating: 'R',
    firstAirYear: 1971,
    decade: '70s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 102,
    director: 'Don Siegel',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Iconic Clint Eastwood Role',
    cast: [
      { name: 'Clint Eastwood', role: 'Inspector \'Dirty\' Harry Callahan' },
      { name: 'Harry Guardino', role: 'Lt. Al Bressler' },
      { name: 'Reni Santoni', role: 'Inspector Chico Gonzalez' },
      { name: 'Andrew Robinson', role: 'Scorpio Killer' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1971-12-23',
        status: 'released',
      },
    ],
  },
  {
    id: 'the-outlaw-josey-wales',
    imdbId: 'tt0075029',
    mediaType: 'movie',
    title: 'The Outlaw Josey Wales',
    tagline: 'An army of men couldn\'t stop him. But one girl might.',
    synopsis: 'A Missouri farmer joins a Confederate guerrilla unit and turns into an outlaw hunted by federal soldiers who murdered his family.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/3/30/The_outlaw_josey_wales_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/3/30/The_outlaw_josey_wales_poster.jpg',
    providers: ['max', 'prime'],
    primaryProvider: 'max',
    genres: ['Western', 'Action', 'Drama'],
    rating: 7.8,
    ratingCount: '85K+',
    contentRating: 'PG',
    firstAirYear: 1976,
    decade: '70s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 135,
    director: 'Clint Eastwood',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Directed by Clint Eastwood',
    cast: [
      { name: 'Clint Eastwood', role: 'Josey Wales' },
      { name: 'Chief Dan George', role: 'Lone Watie' },
      { name: 'Sondra Locke', role: 'Laura Lee' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1976-06-30',
        status: 'released',
      },
    ],
  },
  {
    id: 'escape-from-alcatraz',
    imdbId: 'tt0079116',
    mediaType: 'movie',
    title: 'Escape from Alcatraz',
    tagline: 'No one has ever escaped from Alcatraz... And no one ever will!',
    synopsis: 'Alcatraz is the most secure prison of its time. It is believed that no one can ever escape, until three daring men make a possibly successful attempt at escaping from one of the most infamous federal penitentiaries.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/3/39/Escape_from_Alcatraz_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/3/39/Escape_from_Alcatraz_poster.jpg',
    providers: ['paramount', 'prime'],
    primaryProvider: 'paramount',
    genres: ['Biography', 'Crime', 'Drama', 'Thriller'],
    rating: 7.6,
    ratingCount: '155K+',
    contentRating: 'PG',
    firstAirYear: 1979,
    decade: '70s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 112,
    director: 'Don Siegel',
    network: 'Paramount Pictures',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Starring Clint Eastwood',
    cast: [
      { name: 'Clint Eastwood', role: 'Frank Morris' },
      { name: 'Patrick McGoohan', role: 'Warden' },
      { name: 'Roberts Blossom', role: 'Doc' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1979-06-22',
        status: 'released',
      },
    ],
  },
  {
    id: 'the-godfather',
    imdbId: 'tt0068646',
    mediaType: 'movie',
    title: 'The Godfather',
    tagline: 'An offer you can\'t refuse.',
    synopsis: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant youngest son.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg',
    providers: ['paramount', 'prime'],
    primaryProvider: 'paramount',
    genres: ['Crime', 'Drama'],
    rating: 9.2,
    ratingCount: '2.1M+',
    contentRating: 'R',
    firstAirYear: 1972,
    decade: '70s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 175,
    director: 'Francis Ford Coppola',
    network: 'Paramount+',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Ranked #2 on IMDb Top 250',
    cast: [
      { name: 'Marlon Brando', role: 'Don Vito Corleone' },
      { name: 'Al Pacino', role: 'Michael Corleone' },
      { name: 'James Caan', role: 'Sonny Corleone' },
      { name: 'Robert Duvall', role: 'Tom Hagen' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1972-03-24',
        status: 'released',
      },
    ],
  },
  {
    id: 'the-godfather-part-ii',
    imdbId: 'tt0071562',
    mediaType: 'movie',
    title: 'The Godfather Part II',
    tagline: 'All the power on earth can\'t change destiny.',
    synopsis: 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/0/03/Godfather_part_ii.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/0/03/Godfather_part_ii.jpg',
    providers: ['paramount', 'prime'],
    primaryProvider: 'paramount',
    genres: ['Crime', 'Drama'],
    rating: 9.0,
    ratingCount: '1.4M+',
    contentRating: 'R',
    firstAirYear: 1974,
    decade: '70s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 202,
    director: 'Francis Ford Coppola',
    network: 'Paramount+',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Winner of 6 Academy Awards',
    cast: [
      { name: 'Al Pacino', role: 'Michael Corleone' },
      { name: 'Robert De Niro', role: 'Vito Corleone' },
      { name: 'Robert Duvall', role: 'Tom Hagen' },
      { name: 'Diane Keaton', role: 'Kay Adams' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1974-12-20',
        status: 'released',
      },
    ],
  },
  {
    id: 'taxi-driver',
    imdbId: 'tt0075314',
    mediaType: 'movie',
    title: 'Taxi Driver',
    tagline: 'On every street in every city, there\'s a nobody who dreams of being a somebody.',
    synopsis: 'A mentally unstable veteran works as a nighttime taxi driver in New York City, where the perceived decadence and sleaze fuels his urge for violent action.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/3/33/Taxi_Driver_%281976_film_poster%29.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/3/33/Taxi_Driver_%281976_film_poster%29.jpg',
    providers: ['max', 'prime'],
    primaryProvider: 'max',
    genres: ['Crime', 'Drama'],
    rating: 8.2,
    ratingCount: '920K+',
    contentRating: 'R',
    firstAirYear: 1976,
    decade: '70s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 114,
    director: 'Martin Scorsese',
    network: 'Columbia / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Martin Scorsese & De Niro Classic',
    cast: [
      { name: 'Robert De Niro', role: 'Travis Bickle' },
      { name: 'Jodie Foster', role: 'Iris' },
      { name: 'Cybill Shepherd', role: 'Betsy' },
      { name: 'Harvey Keitel', role: 'Sport' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1976-02-08',
        status: 'released',
      },
    ],
  },
  {
    id: 'apocalypse-now',
    imdbId: 'tt0078788',
    mediaType: 'movie',
    title: 'Apocalypse Now',
    tagline: 'The horror... The horror...',
    synopsis: 'A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c2/Apocalypse_Now_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c2/Apocalypse_Now_poster.jpg',
    providers: ['prime', 'mubi'],
    primaryProvider: 'prime',
    genres: ['Drama', 'Mystery', 'War'],
    rating: 8.4,
    ratingCount: '710K+',
    contentRating: 'R',
    firstAirYear: 1979,
    decade: '70s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 147,
    director: 'Francis Ford Coppola',
    network: 'Zoetrope / Prime Video',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Palme d\'Or Winner',
    cast: [
      { name: 'Martin Sheen', role: 'Captain Benjamin L. Willard' },
      { name: 'Marlon Brando', role: 'Colonel Walter E. Kurtz' },
      { name: 'Robert Duvall', role: 'Lt. Col. Bill Kilgore' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1979-08-15',
        status: 'released',
      },
    ],
  },
  {
    id: 'jaws',
    imdbId: 'tt0073195',
    mediaType: 'movie',
    title: 'Jaws',
    tagline: 'Don\'t go in the water.',
    synopsis: 'When an insatiable great white shark terrorizes the townspeople of Amity Island, the local police chief, a marine biologist, and an old seafarer embark on a desperate hunt.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/e/eb/JAWS_Movie_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/e/eb/JAWS_Movie_poster.jpg',
    providers: ['peacock'],
    primaryProvider: 'peacock',
    genres: ['Adventure', 'Thriller'],
    rating: 8.1,
    ratingCount: '660K+',
    contentRating: 'PG',
    firstAirYear: 1975,
    decade: '70s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 124,
    director: 'Steven Spielberg',
    network: 'Universal / Peacock',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'The Original Summer Blockbuster',
    cast: [
      { name: 'Roy Scheider', role: 'Chief Martin Brody' },
      { name: 'Robert Shaw', role: 'Quint' },
      { name: 'Richard Dreyfuss', role: 'Matt Hooper' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1975-06-20',
        status: 'released',
      },
    ],
  },

  // ==========================================
  // 1980s
  // ==========================================
  {
    id: 'pale-rider',
    imdbId: 'tt0089767',
    mediaType: 'movie',
    title: 'Pale Rider',
    tagline: 'And I looked, and behold a pale horse: and his name that sat on him was Death...',
    synopsis: 'A mysterious preacher protects a humble gold mining camp from a ruthless mining corporation and its corrupt hired gunmen.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4c/Pale_rider.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4c/Pale_rider.jpg',
    providers: ['max', 'prime'],
    primaryProvider: 'max',
    genres: ['Western', 'Drama'],
    rating: 7.3,
    ratingCount: '68K+',
    contentRating: 'R',
    firstAirYear: 1985,
    decade: '80s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 115,
    director: 'Clint Eastwood',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Directed & Starring Clint Eastwood',
    cast: [
      { name: 'Clint Eastwood', role: 'The Preacher' },
      { name: 'Michael Moriarty', role: 'Hull Barret' },
      { name: 'Carrie Snodgress', role: 'Sarah Wheeler' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1985-06-28',
        status: 'released',
      },
    ],
  },
  {
    id: 'blade-runner-1982',
    imdbId: 'tt0083658',
    mediaType: 'movie',
    title: 'Blade Runner',
    tagline: 'Man has made his match... now it\'s his problem.',
    synopsis: 'A blade runner must pursue and terminate four replicants who stole a ship in space and have returned to Earth to find their creator.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9f/Blade_Runner_%281982_poster%29.png',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/9/9f/Blade_Runner_%281982_poster%29.png',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Action', 'Drama', 'Sci-Fi', 'Thriller'],
    rating: 8.1,
    ratingCount: '830K+',
    contentRating: 'R',
    firstAirYear: 1982,
    decade: '80s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 117,
    director: 'Ridley Scott',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Cyberpunk Masterpiece',
    cast: [
      { name: 'Harrison Ford', role: 'Rick Deckard' },
      { name: 'Rutger Hauer', role: 'Roy Batty' },
      { name: 'Sean Young', role: 'Rachael' },
      { name: 'Edward James Olmos', role: 'Gaff' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1982-06-25',
        status: 'released',
      },
    ],
  },
  {
    id: 'the-shining',
    imdbId: 'tt0081505',
    mediaType: 'movie',
    title: 'The Shining',
    tagline: 'A masterpiece of modern horror.',
    synopsis: 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1d/The_Shining_%281980%29_U.K._theatrical_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1d/The_Shining_%281980%29_U.K._theatrical_poster.jpg',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Drama', 'Horror'],
    rating: 8.4,
    ratingCount: '1.1M+',
    contentRating: 'R',
    firstAirYear: 1980,
    decade: '80s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 146,
    director: 'Stanley Kubrick',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Stanley Kubrick Psychological Horror',
    cast: [
      { name: 'Jack Nicholson', role: 'Jack Torrance' },
      { name: 'Shelley Duvall', role: 'Wendy Torrance' },
      { name: 'Danny Lloyd', role: 'Danny Torrance' },
      { name: 'Scatman Crothers', role: 'Dick Hallorann' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1980-05-23',
        status: 'released',
      },
    ],
  },
  {
    id: 'scarface-1983',
    imdbId: 'tt0086250',
    mediaType: 'movie',
    title: 'Scarface',
    tagline: 'He loved the American Dream. With a vengeance.',
    synopsis: 'In 1980 Miami, a determined Cuban immigrant takes over a drug cartel and succumbs to greed and paranoia.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/7/79/Scarface_-_1983_poster.png',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/7/79/Scarface_-_1983_poster.png',
    providers: ['peacock', 'netflix'],
    primaryProvider: 'peacock',
    genres: ['Crime', 'Drama'],
    rating: 8.3,
    ratingCount: '940K+',
    contentRating: 'R',
    firstAirYear: 1983,
    decade: '80s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 170,
    director: 'Brian De Palma',
    network: 'Universal / Peacock',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Al Pacino Crime Classic',
    cast: [
      { name: 'Al Pacino', role: 'Tony Montana' },
      { name: 'Michelle Pfeiffer', role: 'Elvira Hancock' },
      { name: 'Steven Bauer', role: 'Manny Ribera' },
      { name: 'Robert Loggia', role: 'Frank Lopez' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1983-12-09',
        status: 'released',
      },
    ],
  },
  {
    id: 'die-hard',
    imdbId: 'tt0095016',
    mediaType: 'movie',
    title: 'Die Hard',
    tagline: 'Twelve terrorists. One cop. The odds are against John McClane... That\'s just the way he likes it.',
    synopsis: 'A New York City police officer tries to save his estranged wife and several others taken hostage by German terrorists during a Christmas Eve party at the Nakatomi Plaza in Los Angeles.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7e/Die_hard.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7e/Die_hard.jpg',
    providers: ['hulu'],
    primaryProvider: 'hulu',
    genres: ['Action', 'Thriller'],
    rating: 8.2,
    ratingCount: '920K+',
    contentRating: 'R',
    firstAirYear: 1988,
    decade: '80s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 132,
    director: 'John McTiernan',
    network: '20th Century / Hulu',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Definitive Action Masterpiece',
    cast: [
      { name: 'Bruce Willis', role: 'John McClane' },
      { name: 'Alan Rickman', role: 'Hans Gruber' },
      { name: 'Bonnie Bedelia', role: 'Holly Gennero McClane' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1988-07-20',
        status: 'released',
      },
    ],
  },

  // ==========================================
  // 1990s
  // ==========================================
  {
    id: 'unforgiven',
    imdbId: 'tt0105695',
    mediaType: 'movie',
    title: 'Unforgiven',
    tagline: 'It\'s a hell of a thing, killing a man.',
    synopsis: 'Aging outlaw and killer William Munny reluctantly takes on one last job, with the help of his old partner Ned Logan and a young man named The Schofield Kid.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4e/Unforgiven_2.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4e/Unforgiven_2.jpg',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Western', 'Drama'],
    rating: 8.2,
    ratingCount: '440K+',
    contentRating: 'R',
    firstAirYear: 1992,
    decade: '90s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 130,
    director: 'Clint Eastwood',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Winner of 4 Oscars including Best Picture & Director',
    cast: [
      { name: 'Clint Eastwood', role: 'William Munny' },
      { name: 'Gene Hackman', role: 'Little Bill Daggett' },
      { name: 'Morgan Freeman', role: 'Ned Logan' },
      { name: 'Richard Harris', role: 'English Bob' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1992-08-07',
        status: 'released',
      },
    ],
  },
  {
    id: 'the-bridges-of-madison-county',
    imdbId: 'tt0112579',
    mediaType: 'movie',
    title: 'The Bridges of Madison County',
    tagline: 'A love story that captured the hearts of millions.',
    synopsis: 'Photographer Robert Kincaid wanders into the life of housewife Francesca Johnson for four days in the 1960s, forging a profound connection that permanently changes both of their lives.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a2/The_Bridges_of_Madison_County_film_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/a/a2/The_Bridges_of_Madison_County_film_poster.jpg',
    providers: ['max', 'prime'],
    primaryProvider: 'max',
    genres: ['Drama', 'Romance'],
    rating: 7.6,
    ratingCount: '95K+',
    contentRating: 'PG-13',
    firstAirYear: 1995,
    decade: '90s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 135,
    director: 'Clint Eastwood',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Directed & Starring Clint Eastwood',
    cast: [
      { name: 'Clint Eastwood', role: 'Robert Kincaid' },
      { name: 'Meryl Streep', role: 'Francesca Johnson' },
      { name: 'Annie Corley', role: 'Carolyn Johnson' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1995-06-02',
        status: 'released',
      },
    ],
  },
  {
    id: 'the-shawshank-redemption',
    imdbId: 'tt0111161',
    mediaType: 'movie',
    title: 'The Shawshank Redemption',
    tagline: 'Fear can hold you prisoner. Hope can set you free.',
    synopsis: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Drama'],
    rating: 9.3,
    ratingCount: '2.9M+',
    contentRating: 'R',
    firstAirYear: 1994,
    decade: '90s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 142,
    director: 'Frank Darabont',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Ranked #1 on IMDb Top 250',
    cast: [
      { name: 'Tim Robbins', role: 'Andy Dufresne' },
      { name: 'Morgan Freeman', role: 'Ellis Boyd \'Red\' Redding' },
      { name: 'Bob Gunton', role: 'Warden Norton' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1994-09-23',
        status: 'released',
      },
    ],
  },
  {
    id: 'pulp-fiction',
    imdbId: 'tt0110912',
    mediaType: 'movie',
    title: 'Pulp Fiction',
    tagline: 'Girls like me don\'t make invitations like this to just anyone and his brother.',
    synopsis: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/3/3b/Pulp_Fiction_%281994%29_poster.jpg',
    providers: ['paramount', 'max'],
    primaryProvider: 'paramount',
    genres: ['Crime', 'Drama'],
    rating: 8.9,
    ratingCount: '2.2M+',
    contentRating: 'R',
    firstAirYear: 1994,
    decade: '90s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 154,
    director: 'Quentin Tarantino',
    network: 'Miramax / Paramount+',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Quentin Tarantino Masterpiece',
    cast: [
      { name: 'John Travolta', role: 'Vincent Vega' },
      { name: 'Samuel L. Jackson', role: 'Jules Winnfield' },
      { name: 'Uma Thurman', role: 'Mia Wallace' },
      { name: 'Bruce Willis', role: 'Butch Coolidge' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1994-10-14',
        status: 'released',
      },
    ],
  },
  {
    id: 'the-matrix',
    imdbId: 'tt0133093',
    mediaType: 'movie',
    title: 'The Matrix',
    tagline: 'Welcome to the Real World.',
    synopsis: 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth: the life he knows is the elaborate deception of an evil cyber-intelligence.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Action', 'Sci-Fi'],
    rating: 8.7,
    ratingCount: '2.1M+',
    contentRating: 'R',
    firstAirYear: 1999,
    decade: '90s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 136,
    director: 'The Wachowskis',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Sci-Fi Action Revolution',
    cast: [
      { name: 'Keanu Reeves', role: 'Neo' },
      { name: 'Laurence Fishburne', role: 'Morpheus' },
      { name: 'Carrie-Anne Moss', role: 'Trinity' },
      { name: 'Hugo Weaving', role: 'Agent Smith' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1999-03-31',
        status: 'released',
      },
    ],
  },
  {
    id: 'goodfellas',
    imdbId: 'tt0099685',
    mediaType: 'movie',
    title: 'Goodfellas',
    tagline: 'Three Decades of Life in the Mafia.',
    synopsis: 'The story of Henry Hill and his life in the mafia, covering his relationship with his wife Karen and his mob partners Jimmy Conway and Tommy DeVito.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Goodfellas.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/7/7b/Goodfellas.jpg',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Biography', 'Crime', 'Drama'],
    rating: 8.7,
    ratingCount: '1.2M+',
    contentRating: 'R',
    firstAirYear: 1990,
    decade: '90s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 145,
    director: 'Martin Scorsese',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Martin Scorsese Mafia Masterwork',
    cast: [
      { name: 'Robert De Niro', role: 'James \'Jimmy The Gent\' Conway' },
      { name: 'Ray Liotta', role: 'Henry Hill' },
      { name: 'Joe Pesci', role: 'Tommy DeVito' },
      { name: 'Lorraine Bracco', role: 'Karen Hill' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1990-09-21',
        status: 'released',
      },
    ],
  },
  {
    id: 'fight-club',
    imdbId: 'tt0137523',
    mediaType: 'movie',
    title: 'Fight Club',
    tagline: 'Mischief. Mayhem. Soap.',
    synopsis: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg',
    providers: ['hulu'],
    primaryProvider: 'hulu',
    genres: ['Drama'],
    rating: 8.8,
    ratingCount: '2.3M+',
    contentRating: 'R',
    firstAirYear: 1999,
    decade: '90s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 139,
    director: 'David Fincher',
    network: '20th Century / Hulu',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'David Fincher Cult Legend',
    cast: [
      { name: 'Brad Pitt', role: 'Tyler Durden' },
      { name: 'Edward Norton', role: 'The Narrator' },
      { name: 'Helena Bonham Carter', role: 'Marla Singer' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1999-10-15',
        status: 'released',
      },
    ],
  },
  {
    id: 'the-silence-of-the-lambs',
    imdbId: 'tt0102926',
    mediaType: 'movie',
    title: 'The Silence of the Lambs',
    tagline: 'To enter the mind of a killer she must challenge the mind of a madman.',
    synopsis: 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/8/86/The_Silence_of_the_Lambs_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/8/86/The_Silence_of_the_Lambs_poster.jpg',
    providers: ['max', 'prime'],
    primaryProvider: 'max',
    genres: ['Crime', 'Drama', 'Thriller'],
    rating: 8.6,
    ratingCount: '1.5M+',
    contentRating: 'R',
    firstAirYear: 1991,
    decade: '90s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 118,
    director: 'Jonathan Demme',
    network: 'Orion / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Big Five Academy Award Winner',
    cast: [
      { name: 'Jodie Foster', role: 'Clarice Starling' },
      { name: 'Anthony Hopkins', role: 'Dr. Hannibal Lecter' },
      { name: 'Scott Glenn', role: 'Jack Crawford' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1991-02-14',
        status: 'released',
      },
    ],
  },
  {
    id: 'heat-1995',
    imdbId: 'tt0113277',
    mediaType: 'movie',
    title: 'Heat',
    tagline: 'A Los Angeles Crime Saga.',
    synopsis: 'A group of high-end professional thieves start to feel the police closing in when a master detective obsesses over catching them.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6c/Heatposter.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6c/Heatposter.jpg',
    providers: ['max', 'hulu'],
    primaryProvider: 'max',
    genres: ['Action', 'Crime', 'Drama'],
    rating: 8.3,
    ratingCount: '730K+',
    contentRating: 'R',
    firstAirYear: 1995,
    decade: '90s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 170,
    director: 'Michael Mann',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Pacino & De Niro Showdown',
    cast: [
      { name: 'Al Pacino', role: 'Lt. Vincent Hanna' },
      { name: 'Robert De Niro', role: 'Neil McCauley' },
      { name: 'Val Kilmer', role: 'Chris Shiherlis' },
      { name: 'Jon Voight', role: 'Nate' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '1995-12-15',
        status: 'released',
      },
    ],
  },

  // ==========================================
  // 2000s
  // ==========================================
  {
    id: 'gran-torino',
    imdbId: 'tt1205489',
    mediaType: 'movie',
    title: 'Gran Torino',
    tagline: 'Ever notice how you come across somebody once in a while you shouldn\'t have messed with? That\'s me.',
    synopsis: 'Disgruntled Korean War veteran Walt Kowalski sets out to reform his neighbor, Thao Vang Lor, who tried to steal Kowalski\'s prized possession: a 1972 Gran Torino.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c6/Gran_Torino_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/c/c6/Gran_Torino_poster.jpg',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Drama'],
    rating: 8.1,
    ratingCount: '800K+',
    contentRating: 'R',
    firstAirYear: 2008,
    decade: '2000s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 116,
    director: 'Clint Eastwood',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Clint Eastwood Directorial Masterpiece',
    cast: [
      { name: 'Clint Eastwood', role: 'Walt Kowalski' },
      { name: 'Bee Vang', role: 'Thao Vang Lor' },
      { name: 'Ahney Her', role: 'Sue Lor' },
      { name: 'Christopher Carley', role: 'Father Janovich' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '2008-12-12',
        status: 'released',
      },
    ],
  },
  {
    id: 'million-dollar-baby',
    imdbId: 'tt0405159',
    mediaType: 'movie',
    title: 'Million Dollar Baby',
    tagline: 'Beyond his silence, there is a past. Beyond her dreams, there is a feeling.',
    synopsis: 'A determined woman works with a hardened boxing trainer to become a professional, forging an unforgettable bond in the process.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d3/Million_Dollar_Baby_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d3/Million_Dollar_Baby_poster.jpg',
    providers: ['max', 'prime'],
    primaryProvider: 'max',
    genres: ['Drama', 'Sport'],
    rating: 8.1,
    ratingCount: '730K+',
    contentRating: 'PG-13',
    firstAirYear: 2004,
    decade: '2000s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 132,
    director: 'Clint Eastwood',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Winner of 4 Oscars including Best Picture & Director',
    cast: [
      { name: 'Clint Eastwood', role: 'Frankie Dunn' },
      { name: 'Hilary Swank', role: 'Maggie Fitzgerald' },
      { name: 'Morgan Freeman', role: 'Eddie \'Scrap-Iron\' Dupris' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '2004-12-15',
        status: 'released',
      },
    ],
  },
  {
    id: 'the-dark-knight',
    imdbId: 'tt0468569',
    mediaType: 'movie',
    title: 'The Dark Knight',
    tagline: 'Why So Serious?',
    synopsis: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/1/1c/The_Dark_Knight_%282008_film%29.jpg',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Action', 'Crime', 'Drama', 'Thriller'],
    rating: 9.0,
    ratingCount: '2.9M+',
    contentRating: 'PG-13',
    firstAirYear: 2008,
    decade: '2000s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 152,
    director: 'Christopher Nolan',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Ranked #3 on IMDb Top 250',
    cast: [
      { name: 'Christian Bale', role: 'Bruce Wayne / Batman' },
      { name: 'Heath Ledger', role: 'Joker' },
      { name: 'Aaron Eckhart', role: 'Harvey Dent' },
      { name: 'Gary Oldman', role: 'Jim Gordon' },
      { name: 'Michael Caine', role: 'Alfred' },
      { name: 'Morgan Freeman', role: 'Lucius Fox' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '2008-07-18',
        status: 'released',
      },
    ],
  },
  {
    id: 'gladiator-2000',
    imdbId: 'tt0172495',
    mediaType: 'movie',
    title: 'Gladiator',
    tagline: 'A hero will rise.',
    synopsis: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fb/Gladiator_%282000_film_poster%29.png',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/f/fb/Gladiator_%282000_film_poster%29.png',
    providers: ['paramount', 'prime'],
    primaryProvider: 'paramount',
    genres: ['Action', 'Adventure', 'Drama'],
    rating: 8.5,
    ratingCount: '1.6M+',
    contentRating: 'R',
    firstAirYear: 2000,
    decade: '2000s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 155,
    director: 'Ridley Scott',
    network: 'DreamWorks / Paramount+',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Winner of 5 Academy Awards',
    cast: [
      { name: 'Russell Crowe', role: 'Maximus Decimus Meridius' },
      { name: 'Joaquin Phoenix', role: 'Commodus' },
      { name: 'Connie Nielsen', role: 'Lucilla' },
      { name: 'Oliver Reed', role: 'Proximo' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '2000-05-05',
        status: 'released',
      },
    ],
  },
  {
    id: 'the-departed',
    imdbId: 'tt0407887',
    mediaType: 'movie',
    title: 'The Departed',
    tagline: 'Lies. Betrayal. Sacrifice. How far will you take it?',
    synopsis: 'An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/5/50/Departed234.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/5/50/Departed234.jpg',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Crime', 'Drama', 'Thriller'],
    rating: 8.5,
    ratingCount: '1.4M+',
    contentRating: 'R',
    firstAirYear: 2006,
    decade: '2000s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 151,
    director: 'Martin Scorsese',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Scorsese Oscar-Winning Thriller',
    cast: [
      { name: 'Leonardo DiCaprio', role: 'Billy Costigan' },
      { name: 'Matt Damon', role: 'Colin Sullivan' },
      { name: 'Jack Nicholson', role: 'Frank Costello' },
      { name: 'Mark Wahlberg', role: 'Dignam' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '2006-10-06',
        status: 'released',
      },
    ],
  },
  {
    id: 'no-country-for-old-men',
    imdbId: 'tt0477348',
    mediaType: 'movie',
    title: 'No Country for Old Men',
    tagline: 'There are no clean getaways.',
    synopsis: 'Violence and mayhem ensue after a hunter stumbles upon the aftermath of a drug deal gone wrong and more than two million dollars in cash near the Rio Grande.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8b/No_Country_for_Old_Men_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8b/No_Country_for_Old_Men_poster.jpg',
    providers: ['paramount', 'prime'],
    primaryProvider: 'paramount',
    genres: ['Crime', 'Drama', 'Thriller'],
    rating: 8.2,
    ratingCount: '1.1M+',
    contentRating: 'R',
    firstAirYear: 2007,
    decade: '2000s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 122,
    director: 'Joel & Ethan Coen',
    network: 'Miramax / Paramount',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Winner of 4 Academy Awards',
    cast: [
      { name: 'Javier Bardem', role: 'Anton Chigurh' },
      { name: 'Josh Brolin', role: 'Llewelyn Moss' },
      { name: 'Tommy Lee Jones', role: 'Ed Tom Bell' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '2007-11-21',
        status: 'released',
      },
    ],
  },

  // ==========================================
  // 2010s
  // ==========================================
  {
    id: 'the-mule',
    imdbId: 'tt7959026',
    mediaType: 'movie',
    title: 'The Mule',
    tagline: 'Nobody runs forever.',
    synopsis: 'A ninety-year-old horticulturist and Korean War veteran turns into a drug courier for a Mexican cartel in this tense crime drama.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4b/The_Mule_2018_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/4/4b/The_Mule_2018_poster.jpg',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Crime', 'Drama', 'Thriller'],
    rating: 7.0,
    ratingCount: '175K+',
    contentRating: 'R',
    firstAirYear: 2018,
    decade: '2010s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 116,
    director: 'Clint Eastwood',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Directed & Starring Clint Eastwood',
    cast: [
      { name: 'Clint Eastwood', role: 'Earl Stone' },
      { name: 'Bradley Cooper', role: 'Colin Bates' },
      { name: 'Laurence Fishburne', role: 'DEA Special Agent' },
      { name: 'Michael Peña', role: 'Trevino' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '2018-12-14',
        status: 'released',
      },
    ],
  },
  {
    id: 'inception',
    imdbId: 'tt1375666',
    mediaType: 'movie',
    title: 'Inception',
    tagline: 'Your mind is the scene of the crime.',
    synopsis: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/2/2e/Inception_%282010%29_theatrical_poster.jpg',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 8.8,
    ratingCount: '2.6M+',
    contentRating: 'PG-13',
    firstAirYear: 2010,
    decade: '2010s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 148,
    director: 'Christopher Nolan',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Christopher Nolan Mind-Bending Sci-Fi',
    cast: [
      { name: 'Leonardo DiCaprio', role: 'Dom Cobb' },
      { name: 'Joseph Gordon-Levitt', role: 'Arthur' },
      { name: 'Elliot Page', role: 'Ariadne' },
      { name: 'Tom Hardy', role: 'Eames' },
      { name: 'Ken Watanabe', role: 'Saito' },
      { name: 'Cillian Murphy', role: 'Robert Fischer' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '2010-07-16',
        status: 'released',
      },
    ],
  },
  {
    id: 'interstellar',
    imdbId: 'tt0816692',
    mediaType: 'movie',
    title: 'Interstellar',
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    synopsis: 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg',
    providers: ['paramount', 'prime'],
    primaryProvider: 'paramount',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    rating: 8.7,
    ratingCount: '2.1M+',
    contentRating: 'PG-13',
    firstAirYear: 2014,
    decade: '2010s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 169,
    director: 'Christopher Nolan',
    network: 'Paramount / Warner Bros.',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Emotional Sci-Fi Masterpiece',
    cast: [
      { name: 'Matthew McConaughey', role: 'Cooper' },
      { name: 'Anne Hathaway', role: 'Brand' },
      { name: 'Jessica Chastain', role: 'Murph' },
      { name: 'Michael Caine', role: 'Professor Brand' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '2014-11-07',
        status: 'released',
      },
    ],
  },
  {
    id: 'mad-max-fury-road',
    imdbId: 'tt1392190',
    mediaType: 'movie',
    title: 'Mad Max: Fury Road',
    tagline: 'What a Lovely Day.',
    synopsis: 'In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland with the aid of a group of female prisoners, a psychotic worshiper, and a drifter named Max.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6e/Mad_Max_Fury_Road.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/6/6e/Mad_Max_Fury_Road.jpg',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    rating: 8.1,
    ratingCount: '1.1M+',
    contentRating: 'R',
    firstAirYear: 2015,
    decade: '2010s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 120,
    director: 'George Miller',
    network: 'Warner Bros. / Max',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Winner of 6 Academy Awards',
    cast: [
      { name: 'Tom Hardy', role: 'Max Rockatansky' },
      { name: 'Charlize Theron', role: 'Imperator Furiosa' },
      { name: 'Nicholas Hoult', role: 'Nux' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '2015-05-15',
        status: 'released',
      },
    ],
  },
  {
    id: 'whiplash-2014',
    imdbId: 'tt2582802',
    mediaType: 'movie',
    title: 'Whiplash',
    tagline: 'The road to greatness can take you to the edge.',
    synopsis: 'A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student\'s potential.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/0/01/Whiplash_poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/0/01/Whiplash_poster.jpg',
    providers: ['netflix'],
    primaryProvider: 'netflix',
    genres: ['Drama', 'Music'],
    rating: 8.5,
    ratingCount: '1.0M+',
    contentRating: 'R',
    firstAirYear: 2014,
    decade: '2010s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 106,
    director: 'Damien Chazelle',
    network: 'Sony Pictures Classics / Netflix',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Winner of 3 Academy Awards',
    cast: [
      { name: 'Miles Teller', role: 'Andrew Neiman' },
      { name: 'J.K. Simmons', role: 'Terence Fletcher' },
      { name: 'Paul Reiser', role: 'Jim Neiman' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '2014-10-10',
        status: 'released',
      },
    ],
  },
  {
    id: 'the-wolf-of-wall-street',
    imdbId: 'tt0993846',
    mediaType: 'movie',
    title: 'The Wolf of Wall Street',
    tagline: 'Earn. Spend. Party.',
    synopsis: 'Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime, corruption and the federal government.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d8/The_Wolf_of_Wall_Street_%282013%29.png',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/d/d8/The_Wolf_of_Wall_Street_%282013%29.png',
    providers: ['paramount', 'prime'],
    primaryProvider: 'paramount',
    genres: ['Biography', 'Comedy', 'Crime'],
    rating: 8.2,
    ratingCount: '1.5M+',
    contentRating: 'R',
    firstAirYear: 2013,
    decade: '2010s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 180,
    director: 'Martin Scorsese',
    network: 'Paramount+',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Scorsese & DiCaprio Collaboration',
    cast: [
      { name: 'Leonardo DiCaprio', role: 'Jordan Belfort' },
      { name: 'Jonah Hill', role: 'Donnie Azoff' },
      { name: 'Margot Robbie', role: 'Naomi Lapaglia' },
      { name: 'Matthew McConaughey', role: 'Mark Hanna' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '2013-12-25',
        status: 'released',
      },
    ],
  },
  {
    id: 'django-unchained',
    imdbId: 'tt1853728',
    mediaType: 'movie',
    title: 'Django Unchained',
    tagline: 'Life, liberty and the pursuit of vengeance.',
    synopsis: 'With the help of a German bounty-hunter, a freed slave sets out to rescue his wife from a brutal plantation-owner in Mississippi.',
    posterUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8b/Django_Unchained_Poster.jpg',
    backdropUrl: 'https://upload.wikimedia.org/wikipedia/en/8/8b/Django_Unchained_Poster.jpg',
    providers: ['prime'],
    primaryProvider: 'prime',
    genres: ['Drama', 'Western'],
    rating: 8.5,
    ratingCount: '1.7M+',
    contentRating: 'R',
    firstAirYear: 2012,
    decade: '2010s',
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 165,
    director: 'Quentin Tarantino',
    network: 'Weinstein / Columbia / Prime',
    status: 'Released',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    isNextWatch: true,
    renewalState: 'concluded',
    renewalBadgeText: 'Quentin Tarantino Western Masterpiece',
    cast: [
      { name: 'Jamie Foxx', role: 'Django' },
      { name: 'Christoph Waltz', role: 'Dr. King Schultz' },
      { name: 'Leonardo DiCaprio', role: 'Calvin J. Candie' },
      { name: 'Samuel L. Jackson', role: 'Stephen' },
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: 'Feature Film',
        episodeCount: 1,
        releaseDate: '2012-12-25',
        status: 'released',
      },
    ],
  },
  {
  "id": "lawrence-of-arabia",
  "imdbId": "tt0056172",
  "mediaType": "movie",
  "title": "Lawrence of Arabia",
  "tagline": "A towering monument in cinema history.",
  "synopsis": "The story of T.E. Lawrence, the English officer who successfully united and led the diverse, often warring, Arab tribes during World War I to fight the Turks.",
  "posterUrl": "https://upload.wikimedia.org/wikipedia/commons/c/c5/Lawrence_of_arabia_ver3_xxlg.jpg",
  "backdropUrl": "https://upload.wikimedia.org/wikipedia/commons/c/c5/Lawrence_of_arabia_ver3_xxlg.jpg",
  "providers": [
    "max",
    "prime"
  ],
  "primaryProvider": "max",
  "genres": [
    "Adventure",
    "Biography",
    "Drama"
  ],
  "rating": 8.3,
  "ratingCount": "315K+",
  "contentRating": "PG",
  "firstAirYear": 1962,
  "decade": "Pre-70s",
  "totalSeasons": 1,
  "totalEpisodes": 1,
  "runtimeMinutes": 228,
  "director": "David Lean",
  "network": "Columbia Pictures / Max",
  "status": "Released",
  "isNowPlaying": false,
  "isUpcoming": false,
  "isClassic": true,
  "hasNewSeasonAlert": false,
  "isNextWatch": true,
  "renewalState": "concluded",
  "renewalBadgeText": "Winner of 7 Academy Awards",
  "cast": [
    {
      "name": "Peter O'Toole",
      "role": "T.E. Lawrence"
    },
    {
      "name": "Alec Guinness",
      "role": "Prince Faisal"
    },
    {
      "name": "Anthony Quinn",
      "role": "Auda Abu Tayi"
    },
    {
      "name": "Omar Sharif",
      "role": "Sherif Ali"
    }
  ],
  "seasons": [
    {
      "seasonNumber": 1,
      "title": "Feature Film",
      "episodeCount": 1,
      "releaseDate": "1962-12-11",
      "status": "released"
    }
  ]
},
{
  "id": "rear-window",
  "imdbId": "tt0047396",
  "mediaType": "movie",
  "title": "Rear Window",
  "tagline": "Watch out your window... if you dare.",
  "synopsis": "A wheelchair-bound photographer spies on his neighbors from his Greenwich Village courtyard window and becomes convinced one of them has committed murder.",
  "posterUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Rear_Window_film_poster.png/800px-Rear_Window_film_poster.png",
  "backdropUrl": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Rear_Window_film_poster.png/800px-Rear_Window_film_poster.png",
  "providers": [
    "peacock",
    "prime"
  ],
  "primaryProvider": "peacock",
  "genres": [
    "Mystery",
    "Thriller"
  ],
  "rating": 8.5,
  "ratingCount": "520K+",
  "contentRating": "PG",
  "firstAirYear": 1954,
  "decade": "Pre-70s",
  "totalSeasons": 1,
  "totalEpisodes": 1,
  "runtimeMinutes": 112,
  "director": "Alfred Hitchcock",
  "network": "Paramount Pictures / Peacock",
  "status": "Released",
  "isNowPlaying": false,
  "isUpcoming": false,
  "isClassic": true,
  "hasNewSeasonAlert": false,
  "isNextWatch": true,
  "renewalState": "concluded",
  "renewalBadgeText": "Hitchcock Mystery Perfection",
  "cast": [
    {
      "name": "James Stewart",
      "role": "L.B. 'Jeff' Jefferies"
    },
    {
      "name": "Grace Kelly",
      "role": "Lisa Carol Fremont"
    },
    {
      "name": "Wendell Corey",
      "role": "Det. Thomas J. Doyle"
    },
    {
      "name": "Thelma Ritter",
      "role": "Stella"
    }
  ],
  "seasons": [
    {
      "seasonNumber": 1,
      "title": "Feature Film",
      "episodeCount": 1,
      "releaseDate": "1954-09-01",
      "status": "released"
    }
  ]
},
{
  "id": "alien-1979",
  "imdbId": "tt0078748",
  "mediaType": "movie",
  "title": "Alien",
  "tagline": "In space no one can hear you scream.",
  "synopsis": "The crew of a commercial spacecraft encounter a deadly lifeform after investigating an unknown transmission on a desolate moon.",
  "posterUrl": "https://upload.wikimedia.org/wikipedia/en/c/c3/Alien_movie_poster.jpg",
  "backdropUrl": "https://upload.wikimedia.org/wikipedia/en/c/c3/Alien_movie_poster.jpg",
  "providers": [
    "hulu",
    "prime"
  ],
  "primaryProvider": "hulu",
  "genres": [
    "Horror",
    "Sci-Fi"
  ],
  "rating": 8.5,
  "ratingCount": "940K+",
  "contentRating": "R",
  "firstAirYear": 1979,
  "decade": "70s",
  "totalSeasons": 1,
  "totalEpisodes": 1,
  "runtimeMinutes": 117,
  "director": "Ridley Scott",
  "network": "20th Century Fox / Hulu",
  "status": "Released",
  "isNowPlaying": false,
  "isUpcoming": false,
  "isClassic": true,
  "hasNewSeasonAlert": false,
  "isNextWatch": true,
  "renewalState": "concluded",
  "renewalBadgeText": "Sci-Fi Horror Defining Landmark",
  "cast": [
    {
      "name": "Sigourney Weaver",
      "role": "Ellen Ripley"
    },
    {
      "name": "Tom Skerritt",
      "role": "Dallas"
    },
    {
      "name": "John Hurt",
      "role": "Kane"
    },
    {
      "name": "Ian Holm",
      "role": "Ash"
    }
  ],
  "seasons": [
    {
      "seasonNumber": 1,
      "title": "Feature Film",
      "episodeCount": 1,
      "releaseDate": "1979-05-25",
      "status": "released"
    }
  ]
},
{
  "id": "rocky-1976",
  "imdbId": "tt0075148",
  "mediaType": "movie",
  "title": "Rocky",
  "tagline": "His whole life was a million-to-one shot.",
  "synopsis": "A small-time Philadelphia boxer gets a supremely rare chance to fight world heavyweight champion Apollo Creed in a bout in which he strives to go the distance.",
  "posterUrl": "https://upload.wikimedia.org/wikipedia/en/1/18/Rocky_poster.jpg",
  "backdropUrl": "https://upload.wikimedia.org/wikipedia/en/1/18/Rocky_poster.jpg",
  "providers": [
    "prime",
    "max"
  ],
  "primaryProvider": "prime",
  "genres": [
    "Drama",
    "Sport"
  ],
  "rating": 8.1,
  "ratingCount": "610K+",
  "contentRating": "PG",
  "firstAirYear": 1976,
  "decade": "70s",
  "totalSeasons": 1,
  "totalEpisodes": 1,
  "runtimeMinutes": 120,
  "director": "John G. Avildsen",
  "network": "United Artists / Prime Video",
  "status": "Released",
  "isNowPlaying": false,
  "isUpcoming": false,
  "isClassic": true,
  "hasNewSeasonAlert": false,
  "isNextWatch": true,
  "renewalState": "concluded",
  "renewalBadgeText": "Best Picture Academy Award Winner",
  "cast": [
    {
      "name": "Sylvester Stallone",
      "role": "Rocky Balboa"
    },
    {
      "name": "Talia Shire",
      "role": "Adrian Pennino"
    },
    {
      "name": "Burt Young",
      "role": "Paulie Pennino"
    },
    {
      "name": "Carl Weathers",
      "role": "Apollo Creed"
    }
  ],
  "seasons": [
    {
      "seasonNumber": 1,
      "title": "Feature Film",
      "episodeCount": 1,
      "releaseDate": "1976-12-03",
      "status": "released"
    }
  ]
},
{
  "id": "back-to-the-future",
  "imdbId": "tt0088763",
  "mediaType": "movie",
  "title": "Back to the Future",
  "tagline": "He's the only kid ever to get into trouble before he was even born.",
  "synopsis": "Marty McFly, a 17-year-old high school student, is accidentally sent 30 years into the past in a time-traveling DeLorean invented by his close friend Doc Brown.",
  "posterUrl": "https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg",
  "backdropUrl": "https://upload.wikimedia.org/wikipedia/en/d/d2/Back_to_the_Future.jpg",
  "providers": [
    "peacock",
    "prime"
  ],
  "primaryProvider": "peacock",
  "genres": [
    "Adventure",
    "Comedy",
    "Sci-Fi"
  ],
  "rating": 8.5,
  "ratingCount": "1.3M+",
  "contentRating": "PG",
  "firstAirYear": 1985,
  "decade": "80s",
  "totalSeasons": 1,
  "totalEpisodes": 1,
  "runtimeMinutes": 116,
  "director": "Robert Zemeckis",
  "network": "Universal Pictures / Peacock",
  "status": "Released",
  "isNowPlaying": false,
  "isUpcoming": false,
  "isClassic": true,
  "hasNewSeasonAlert": false,
  "isNextWatch": true,
  "renewalState": "concluded",
  "renewalBadgeText": "Beloved 80s Sci-Fi Adventure",
  "cast": [
    {
      "name": "Michael J. Fox",
      "role": "Marty McFly"
    },
    {
      "name": "Christopher Lloyd",
      "role": "Dr. Emmett Brown"
    },
    {
      "name": "Lea Thompson",
      "role": "Lorraine Baines"
    },
    {
      "name": "Crispin Glover",
      "role": "George McFly"
    }
  ],
  "seasons": [
    {
      "seasonNumber": 1,
      "title": "Feature Film",
      "episodeCount": 1,
      "releaseDate": "1985-07-03",
      "status": "released"
    }
  ]
},
{
  "id": "raiders-of-the-lost-ark",
  "imdbId": "tt0082971",
  "mediaType": "movie",
  "title": "Raiders of the Lost Ark",
  "tagline": "Indiana Jones - the new hero from the creators of Jaws and Star Wars.",
  "synopsis": "In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before Adolf Hitler's forces can obtain its awesome powers.",
  "posterUrl": "https://upload.wikimedia.org/wikipedia/en/4/4c/Raiders_of_the_Lost_Ark.jpg",
  "backdropUrl": "https://upload.wikimedia.org/wikipedia/en/4/4c/Raiders_of_the_Lost_Ark.jpg",
  "providers": [
    "paramount",
    "prime"
  ],
  "primaryProvider": "paramount",
  "genres": [
    "Action",
    "Adventure"
  ],
  "rating": 8.4,
  "ratingCount": "1.1M+",
  "contentRating": "PG",
  "firstAirYear": 1981,
  "decade": "80s",
  "totalSeasons": 1,
  "totalEpisodes": 1,
  "runtimeMinutes": 115,
  "director": "Steven Spielberg",
  "network": "Lucasfilm / Paramount",
  "status": "Released",
  "isNowPlaying": false,
  "isUpcoming": false,
  "isClassic": true,
  "hasNewSeasonAlert": false,
  "isNextWatch": true,
  "renewalState": "concluded",
  "renewalBadgeText": "Definitive Adventure Masterpiece",
  "cast": [
    {
      "name": "Harrison Ford",
      "role": "Indiana Jones"
    },
    {
      "name": "Karen Allen",
      "role": "Marion Ravenwood"
    },
    {
      "name": "Paul Freeman",
      "role": "Dr. René Belloq"
    },
    {
      "name": "John Rhys-Davies",
      "role": "Sallah"
    }
  ],
  "seasons": [
    {
      "seasonNumber": 1,
      "title": "Feature Film",
      "episodeCount": 1,
      "releaseDate": "1981-06-12",
      "status": "released"
    }
  ]
},
{
  "id": "the-terminator",
  "imdbId": "tt0088247",
  "mediaType": "movie",
  "title": "The Terminator",
  "tagline": "Your future is in its hands.",
  "synopsis": "A human soldier is sent from 2029 to 1984 to protect a young waitress from an indestructible cyborg killing machine sent to eliminate her before she gives birth to the leader of human resistance.",
  "posterUrl": "https://upload.wikimedia.org/wikipedia/en/7/70/Terminator1984movieposter.jpg",
  "backdropUrl": "https://upload.wikimedia.org/wikipedia/en/7/70/Terminator1984movieposter.jpg",
  "providers": [
    "max",
    "prime"
  ],
  "primaryProvider": "max",
  "genres": [
    "Action",
    "Sci-Fi"
  ],
  "rating": 8.1,
  "ratingCount": "930K+",
  "contentRating": "R",
  "firstAirYear": 1984,
  "decade": "80s",
  "totalSeasons": 1,
  "totalEpisodes": 1,
  "runtimeMinutes": 107,
  "director": "James Cameron",
  "network": "Orion Pictures / Max",
  "status": "Released",
  "isNowPlaying": false,
  "isUpcoming": false,
  "isClassic": true,
  "hasNewSeasonAlert": false,
  "isNextWatch": true,
  "renewalState": "concluded",
  "renewalBadgeText": "James Cameron Sci-Fi Breakthrough",
  "cast": [
    {
      "name": "Arnold Schwarzenegger",
      "role": "The Terminator"
    },
    {
      "name": "Michael Biehn",
      "role": "Kyle Reese"
    },
    {
      "name": "Linda Hamilton",
      "role": "Sarah Connor"
    },
    {
      "name": "Paul Winfield",
      "role": "Lt. Ed Traxler"
    }
  ],
  "seasons": [
    {
      "seasonNumber": 1,
      "title": "Feature Film",
      "episodeCount": 1,
      "releaseDate": "1984-10-26",
      "status": "released"
    }
  ]
},
{
  "id": "jurassic-park-1993",
  "imdbId": "tt0107290",
  "mediaType": "movie",
  "title": "Jurassic Park",
  "tagline": "An adventure 65 million years in the making.",
  "synopsis": "A pragmatic paleontologist touring an almost complete theme park on an island in Central America is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
  "posterUrl": "https://upload.wikimedia.org/wikipedia/en/e/e0/Jurassic_Park_poster.jpg",
  "backdropUrl": "https://upload.wikimedia.org/wikipedia/en/e/e0/Jurassic_Park_poster.jpg",
  "providers": [
    "peacock",
    "prime"
  ],
  "primaryProvider": "peacock",
  "genres": [
    "Action",
    "Adventure",
    "Sci-Fi"
  ],
  "rating": 8.2,
  "ratingCount": "1.1M+",
  "contentRating": "PG-13",
  "firstAirYear": 1993,
  "decade": "90s",
  "totalSeasons": 1,
  "totalEpisodes": 1,
  "runtimeMinutes": 127,
  "director": "Steven Spielberg",
  "network": "Universal Pictures / Peacock",
  "status": "Released",
  "isNowPlaying": false,
  "isUpcoming": false,
  "isClassic": true,
  "hasNewSeasonAlert": false,
  "isNextWatch": true,
  "renewalState": "concluded",
  "renewalBadgeText": "CGI & Cinematic Milsetone",
  "cast": [
    {
      "name": "Sam Neill",
      "role": "Dr. Alan Grant"
    },
    {
      "name": "Laura Dern",
      "role": "Dr. Ellie Sattler"
    },
    {
      "name": "Jeff Goldblum",
      "role": "Dr. Ian Malcolm"
    },
    {
      "name": "Richard Attenborough",
      "role": "John Hammond"
    }
  ],
  "seasons": [
    {
      "seasonNumber": 1,
      "title": "Feature Film",
      "episodeCount": 1,
      "releaseDate": "1993-06-11",
      "status": "released"
    }
  ]
},
{
  "id": "se7en",
  "imdbId": "tt0114369",
  "mediaType": "movie",
  "title": "Se7en",
  "tagline": "Seven deadly sins. Seven ways to die.",
  "synopsis": "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives in a dark, rain-soaked metropolis.",
  "posterUrl": "https://upload.wikimedia.org/wikipedia/en/6/68/Seven_%28movie%29_poster.jpg",
  "backdropUrl": "https://upload.wikimedia.org/wikipedia/en/6/68/Seven_%28movie%29_poster.jpg",
  "providers": [
    "max",
    "prime"
  ],
  "primaryProvider": "max",
  "genres": [
    "Crime",
    "Drama",
    "Mystery",
    "Thriller"
  ],
  "rating": 8.6,
  "ratingCount": "1.8M+",
  "contentRating": "R",
  "firstAirYear": 1995,
  "decade": "90s",
  "totalSeasons": 1,
  "totalEpisodes": 1,
  "runtimeMinutes": 127,
  "director": "David Fincher",
  "network": "New Line Cinema / Max",
  "status": "Released",
  "isNowPlaying": false,
  "isUpcoming": false,
  "isClassic": true,
  "hasNewSeasonAlert": false,
  "isNextWatch": true,
  "renewalState": "concluded",
  "renewalBadgeText": "Fincher Neo-Noir Masterpiece",
  "cast": [
    {
      "name": "Morgan Freeman",
      "role": "Detective Lt. William Somerset"
    },
    {
      "name": "Brad Pitt",
      "role": "Detective David Mills"
    },
    {
      "name": "Gwyneth Paltrow",
      "role": "Tracy Mills"
    },
    {
      "name": "Kevin Spacey",
      "role": "John Doe"
    }
  ],
  "seasons": [
    {
      "seasonNumber": 1,
      "title": "Feature Film",
      "episodeCount": 1,
      "releaseDate": "1995-09-22",
      "status": "released"
    }
  ]
},
{
  "id": "the-lord-of-the-rings-fellowship",
  "imdbId": "tt0120737",
  "mediaType": "movie",
  "title": "The Lord of the Rings: The Fellowship of the Ring",
  "tagline": "One ring to rule them all.",
  "synopsis": "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.",
  "posterUrl": "https://upload.wikimedia.org/wikipedia/en/8/8a/The_Lord_of_the_Rings_The_Fellowship_of_the_Ring_%282001%29.jpg",
  "backdropUrl": "https://upload.wikimedia.org/wikipedia/en/8/8a/The_Lord_of_the_Rings_The_Fellowship_of_the_Ring_%282001%29.jpg",
  "providers": [
    "max",
    "prime"
  ],
  "primaryProvider": "max",
  "genres": [
    "Action",
    "Adventure",
    "Drama",
    "Fantasy"
  ],
  "rating": 8.9,
  "ratingCount": "2.1M+",
  "contentRating": "PG-13",
  "firstAirYear": 2001,
  "decade": "2000s",
  "totalSeasons": 1,
  "totalEpisodes": 1,
  "runtimeMinutes": 178,
  "director": "Peter Jackson",
  "network": "New Line Cinema / Max",
  "status": "Released",
  "isNowPlaying": false,
  "isUpcoming": false,
  "isClassic": true,
  "hasNewSeasonAlert": false,
  "isNextWatch": true,
  "renewalState": "concluded",
  "renewalBadgeText": "High Fantasy Landmark Epic",
  "cast": [
    {
      "name": "Elijah Wood",
      "role": "Frodo Baggins"
    },
    {
      "name": "Ian McKellen",
      "role": "Gandalf"
    },
    {
      "name": "Viggo Mortensen",
      "role": "Aragorn"
    },
    {
      "name": "Sean Astin",
      "role": "Samwise Gamgee"
    }
  ],
  "seasons": [
    {
      "seasonNumber": 1,
      "title": "Feature Film",
      "episodeCount": 1,
      "releaseDate": "2001-12-19",
      "status": "released"
    }
  ]
},
{
  "id": "memento",
  "imdbId": "tt0209144",
  "mediaType": "movie",
  "title": "Memento",
  "tagline": "Some memories are best forgotten.",
  "synopsis": "A man with short-term memory loss attempts to track down his wife's murderer using notes, polaroid photos, and tattoos on his body.",
  "posterUrl": "https://upload.wikimedia.org/wikipedia/en/c/c7/Memento_poster.jpg",
  "backdropUrl": "https://upload.wikimedia.org/wikipedia/en/c/c7/Memento_poster.jpg",
  "providers": [
    "prime",
    "peacock"
  ],
  "primaryProvider": "prime",
  "genres": [
    "Mystery",
    "Thriller"
  ],
  "rating": 8.4,
  "ratingCount": "1.3M+",
  "contentRating": "R",
  "firstAirYear": 2000,
  "decade": "2000s",
  "totalSeasons": 1,
  "totalEpisodes": 1,
  "runtimeMinutes": 113,
  "director": "Christopher Nolan",
  "network": "Newmarket Films / Prime Video",
  "status": "Released",
  "isNowPlaying": false,
  "isUpcoming": false,
  "isClassic": true,
  "hasNewSeasonAlert": false,
  "isNextWatch": true,
  "renewalState": "concluded",
  "renewalBadgeText": "Nolan Non-Linear Masterwork",
  "cast": [
    {
      "name": "Guy Pearce",
      "role": "Leonard Shelby"
    },
    {
      "name": "Carrie-Anne Moss",
      "role": "Natalie"
    },
    {
      "name": "Joe Pantoliano",
      "role": "Teddy"
    }
  ],
  "seasons": [
    {
      "seasonNumber": 1,
      "title": "Feature Film",
      "episodeCount": 1,
      "releaseDate": "2000-09-05",
      "status": "released"
    }
  ]
},
{
  "id": "there-will-be-blood",
  "imdbId": "tt0469494",
  "mediaType": "movie",
  "title": "There Will Be Blood",
  "tagline": "There will be blood.",
  "synopsis": "A ruthless prospector turns into a merciless oil tycoon during Southern California's oil boom in the late 19th and early 20th centuries, clashing fiercely with a charismatic local preacher.",
  "posterUrl": "https://upload.wikimedia.org/wikipedia/en/d/da/There_Will_Be_Blood_Poster.jpg",
  "backdropUrl": "https://upload.wikimedia.org/wikipedia/en/d/da/There_Will_Be_Blood_Poster.jpg",
  "providers": [
    "paramount",
    "prime"
  ],
  "primaryProvider": "paramount",
  "genres": [
    "Drama"
  ],
  "rating": 8.2,
  "ratingCount": "640K+",
  "contentRating": "R",
  "firstAirYear": 2007,
  "decade": "2000s",
  "totalSeasons": 1,
  "totalEpisodes": 1,
  "runtimeMinutes": 158,
  "director": "Paul Thomas Anderson",
  "network": "Paramount Vantage / Miramax",
  "status": "Released",
  "isNowPlaying": false,
  "isUpcoming": false,
  "isClassic": true,
  "hasNewSeasonAlert": false,
  "isNextWatch": true,
  "renewalState": "concluded",
  "renewalBadgeText": "Daniel Day-Lewis Oscar-Winning Tour de Force",
  "cast": [
    {
      "name": "Daniel Day-Lewis",
      "role": "Daniel Plainview"
    },
    {
      "name": "Paul Dano",
      "role": "Paul Sunday / Eli Sunday"
    },
    {
      "name": "Kevin J. O'Connor",
      "role": "Henry"
    }
  ],
  "seasons": [
    {
      "seasonNumber": 1,
      "title": "Feature Film",
      "episodeCount": 1,
      "releaseDate": "2007-12-26",
      "status": "released"
    }
  ]
},
{
  "id": "parasite-2019",
  "imdbId": "tt6751668",
  "mediaType": "movie",
  "title": "Parasite",
  "tagline": "Act like you own the place.",
  "synopsis": "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
  "posterUrl": "https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29_poster.jpg",
  "backdropUrl": "https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29_poster.jpg",
  "providers": [
    "max",
    "hulu"
  ],
  "primaryProvider": "max",
  "genres": [
    "Drama",
    "Thriller"
  ],
  "rating": 8.5,
  "ratingCount": "940K+",
  "contentRating": "R",
  "firstAirYear": 2019,
  "decade": "2010s",
  "totalSeasons": 1,
  "totalEpisodes": 1,
  "runtimeMinutes": 132,
  "director": "Bong Joon-ho",
  "network": "CJ Entertainment / Neon / Max",
  "status": "Released",
  "isNowPlaying": false,
  "isUpcoming": false,
  "isClassic": true,
  "hasNewSeasonAlert": false,
  "isNextWatch": true,
  "renewalState": "concluded",
  "renewalBadgeText": "Historic 4-Time Oscar Winner & Palme d'Or",
  "cast": [
    {
      "name": "Song Kang-ho",
      "role": "Kim Ki-taek"
    },
    {
      "name": "Lee Sun-kyun",
      "role": "Park Dong-ik"
    },
    {
      "name": "Cho Yeo-jeong",
      "role": "Choi Yeon-gyo"
    },
    {
      "name": "Choi Woo-shik",
      "role": "Kim Ki-woo"
    }
  ],
  "seasons": [
    {
      "seasonNumber": 1,
      "title": "Feature Film",
      "episodeCount": 1,
      "releaseDate": "2019-05-30",
      "status": "released"
    }
  ]
},
{
  "id": "blade-runner-2049",
  "imdbId": "tt1856101",
  "mediaType": "movie",
  "title": "Blade Runner 2049",
  "tagline": "The key to the future is finally unearthed.",
  "synopsis": "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
  "posterUrl": "https://upload.wikimedia.org/wikipedia/en/9/9b/Blade_Runner_2049_logo.png",
  "backdropUrl": "https://upload.wikimedia.org/wikipedia/en/9/9b/Blade_Runner_2049_logo.png",
  "providers": [
    "max",
    "prime"
  ],
  "primaryProvider": "max",
  "genres": [
    "Action",
    "Drama",
    "Mystery",
    "Sci-Fi"
  ],
  "rating": 8,
  "ratingCount": "660K+",
  "contentRating": "R",
  "firstAirYear": 2017,
  "decade": "2010s",
  "totalSeasons": 1,
  "totalEpisodes": 1,
  "runtimeMinutes": 164,
  "director": "Denis Villeneuve",
  "network": "Warner Bros. / Sony / Max",
  "status": "Released",
  "isNowPlaying": false,
  "isUpcoming": false,
  "isClassic": true,
  "hasNewSeasonAlert": false,
  "isNextWatch": true,
  "renewalState": "concluded",
  "renewalBadgeText": "Denis Villeneuve Sci-Fi Landmark",
  "cast": [
    {
      "name": "Ryan Gosling",
      "role": "K"
    },
    {
      "name": "Harrison Ford",
      "role": "Rick Deckard"
    },
    {
      "name": "Ana de Armas",
      "role": "Joi"
    },
    {
      "name": "Sylvia Hoeks",
      "role": "Luv"
    }
  ],
  "seasons": [
    {
      "seasonNumber": 1,
      "title": "Feature Film",
      "episodeCount": 1,
      "releaseDate": "2017-10-06",
      "status": "released"
    }
  ]
}
];
