import { Series, StreamingProvider } from '../src/types';

export const PROVIDERS: StreamingProvider[] = [
  {
    id: 'all',
    name: 'All Providers',
    badgeColor: 'bg-zinc-800 text-zinc-100',
    bgColor: 'bg-zinc-900',
    textColor: 'text-zinc-100',
    iconName: 'Tv',
    accentColor: '#6366f1',
  },
  {
    id: 'netflix',
    name: 'Netflix',
    badgeColor: 'bg-red-600/20 text-red-400 border-red-500/30',
    bgColor: 'bg-[#E50914]',
    textColor: 'text-white',
    iconName: 'Play',
    accentColor: '#E50914',
  },
  {
    id: 'appletv',
    name: 'Apple TV+',
    badgeColor: 'bg-zinc-600/20 text-zinc-300 border-zinc-500/30',
    bgColor: 'bg-zinc-800',
    textColor: 'text-white',
    iconName: 'Film',
    accentColor: '#a1a1aa',
  },
  {
    id: 'max',
    name: 'Max (HBO)',
    badgeColor: 'bg-blue-600/20 text-blue-400 border-blue-500/30',
    bgColor: 'bg-[#002BE7]',
    textColor: 'text-white',
    iconName: 'Sparkles',
    accentColor: '#002BE7',
  },
  {
    id: 'prime',
    name: 'Prime Video',
    badgeColor: 'bg-sky-600/20 text-sky-400 border-sky-500/30',
    bgColor: 'bg-[#00A8E1]',
    textColor: 'text-white',
    iconName: 'Video',
    accentColor: '#00A8E1',
  },
  {
    id: 'disney',
    name: 'Disney+',
    badgeColor: 'bg-cyan-600/20 text-cyan-400 border-cyan-500/30',
    bgColor: 'bg-[#113CCF]',
    textColor: 'text-white',
    iconName: 'Zap',
    accentColor: '#113CCF',
  },
  {
    id: 'hulu',
    name: 'Hulu',
    badgeColor: 'bg-emerald-600/20 text-emerald-400 border-emerald-500/30',
    bgColor: 'bg-[#1CE783]',
    textColor: 'text-zinc-950',
    iconName: 'MonitorPlay',
    accentColor: '#1CE783',
  },
  {
    id: 'paramount',
    name: 'Paramount+',
    badgeColor: 'bg-indigo-600/20 text-indigo-400 border-indigo-500/30',
    bgColor: 'bg-[#0064FF]',
    textColor: 'text-white',
    iconName: 'Mountain',
    accentColor: '#0064FF',
  },
  {
    id: 'peacock',
    name: 'Peacock',
    badgeColor: 'bg-amber-600/20 text-amber-400 border-amber-500/30',
    bgColor: 'bg-[#000000]',
    textColor: 'text-white',
    iconName: 'Feather',
    accentColor: '#EAA800',
  }
];

export const INITIAL_SERIES_DATABASE: Series[] = [
  // --- NOW PLAYING / FRESH ACTIVE SERIES ---
  {
    id: 'severance',
    title: 'Severance',
    tagline: 'Please do not attempt to adjust your memory.',
    synopsis: 'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about their job.',
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&auto=format&fit=crop&q=80',
    providers: ['appletv'],
    primaryProvider: 'appletv',
    genres: ['Sci-Fi', 'Psychological Thriller', 'Mystery', 'Drama'],
    rating: 8.7,
    ratingCount: '190K+',
    contentRating: 'TV-MA',
    firstAirYear: 2022,
    decade: '2020s',
    totalSeasons: 2,
    totalEpisodes: 19,
    status: 'Returning Series',
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: true,
    renewalState: 'renewed',
    renewalBadgeText: 'Renewed for Season 3',
    nextSeasonNumber: 3,
    nextSeasonReleaseDate: '2027-01-15',
    nextSeasonDaysLeft: 150,
    renewalNewsSummary: 'Officially renewed for Season 3 by Apple TV+ following massive acclaim for Season 2.',
    productionNotes: 'Showrunner Dan Erickson and Ben Stiller are developing Season 3 scripts.',
    creator: 'Dan Erickson',
    network: 'Apple TV+',
    cast: [
      { name: 'Adam Scott', role: 'Mark Scout' },
      { name: 'Britt Lower', role: 'Helly R.' },
      { name: 'Patricia Arquette', role: 'Harmony Cobel' },
      { name: 'John Turturro', role: 'Irving Bailiff' },
      { name: 'Christopher Walken', role: 'Burt Goodman' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 9, releaseDate: '2022-02-18', status: 'released', overview: 'Mark Scout leads an office whose work memories are severed.' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 10, releaseDate: '2025-01-17', status: 'released', overview: 'The MDR team grapples with the fallout of the Overtime Contingency.' },
      { seasonNumber: 3, title: 'Season 3', episodeCount: 10, releaseDate: '2027-01-15', status: 'upcoming', countdownDays: 150, overview: 'The struggle expands into the higher echelons of Lumon Industries.' }
    ]
  },
  {
    id: 'the-last-of-us',
    title: 'The Last of Us',
    tagline: 'When you\'re lost in the darkness, look for the light.',
    synopsis: 'After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity\'s last hope.',
    posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Post-Apocalyptic', 'Drama', 'Action', 'Horror'],
    rating: 8.8,
    ratingCount: '520K+',
    contentRating: 'TV-MA',
    firstAirYear: 2023,
    decade: '2020s',
    totalSeasons: 2,
    totalEpisodes: 16,
    status: 'Returning Series',
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: true,
    renewalState: 'season_upcoming',
    renewalBadgeText: 'Season 2 Premiering Soon',
    nextSeasonNumber: 2,
    nextSeasonReleaseDate: '2026-09-20',
    nextSeasonDaysLeft: 33,
    renewalNewsSummary: 'HBO confirmed Season 2 will adapt the pivotal Seattle and Jackson storylines from Part II.',
    productionNotes: 'Craig Mazin and Neil Druckmann have announced plans spanning across multiple seasons for Part II storyline.',
    creator: 'Craig Mazin & Neil Druckmann',
    network: 'HBO / Max',
    cast: [
      { name: 'Pedro Pascal', role: 'Joel Miller' },
      { name: 'Bella Ramsey', role: 'Ellie Williams' },
      { name: 'Kaitlyn Dever', role: 'Abby Anderson' },
      { name: 'Isabela Merced', role: 'Dina' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 9, releaseDate: '2023-01-15', status: 'released', overview: 'Joel and Ellie travel across a devastated America.' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 7, releaseDate: '2026-09-20', status: 'upcoming', countdownDays: 33, overview: 'Five years after their dangerous journey, a violent event disrupts peace in Jackson.' }
    ]
  },
  {
    id: 'stranger-things',
    title: 'Stranger Things',
    tagline: 'Every ending has a beginning.',
    synopsis: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.',
    posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1600&auto=format&fit=crop&q=80',
    providers: ['netflix'],
    primaryProvider: 'netflix',
    genres: ['Sci-Fi', 'Supernatural Horror', 'Drama', 'Adventure'],
    rating: 8.7,
    ratingCount: '1.3M+',
    contentRating: 'TV-14',
    firstAirYear: 2016,
    decade: '2010s',
    totalSeasons: 5,
    totalEpisodes: 42,
    status: 'Returning Series',
    isNowPlaying: false,
    isUpcoming: true,
    isClassic: false,
    hasNewSeasonAlert: true,
    renewalState: 'final_season_upcoming',
    renewalBadgeText: 'Final Season 5 (Upcoming)',
    nextSeasonNumber: 5,
    nextSeasonReleaseDate: '2026-11-06',
    nextSeasonDaysLeft: 80,
    renewalNewsSummary: 'Season 5 marks the epic conclusion to the Hawkins saga with feature-film length episodes.',
    productionNotes: 'Filming completed in Atlanta. Duffer Brothers confirmed no reset or new characters.',
    creator: 'The Duffer Brothers',
    network: 'Netflix',
    cast: [
      { name: 'Millie Bobby Brown', role: 'Eleven' },
      { name: 'David Harbour', role: 'Jim Hopper' },
      { name: 'Winona Ryder', role: 'Joyce Byers' },
      { name: 'Finn Wolfhard', role: 'Mike Wheeler' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 8, releaseDate: '2016-07-15', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 9, releaseDate: '2017-10-27', status: 'released' },
      { seasonNumber: 3, title: 'Season 3', episodeCount: 8, releaseDate: '2019-07-04', status: 'released' },
      { seasonNumber: 4, title: 'Season 4', episodeCount: 9, releaseDate: '2022-05-27', status: 'released' },
      { seasonNumber: 5, title: 'Season 5 (Final)', episodeCount: 8, releaseDate: '2026-11-06', status: 'upcoming', countdownDays: 80, overview: 'The final battle against Vecna and the Upside Down in Hawkins.' }
    ]
  },
  {
    id: 'house-of-the-dragon',
    title: 'House of the Dragon',
    tagline: 'Fire will reign.',
    synopsis: 'The story of the House Targaryen, set 200 years before the events of Game of Thrones, chronicling the beginning of the end of House Targaryen.',
    posterUrl: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=1600&auto=format&fit=crop&q=80',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Fantasy', 'Action', 'Drama', 'Epic'],
    rating: 8.4,
    ratingCount: '410K+',
    contentRating: 'TV-MA',
    firstAirYear: 2022,
    decade: '2020s',
    totalSeasons: 3,
    totalEpisodes: 26,
    status: 'Returning Series',
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: true,
    renewalState: 'in_production',
    renewalBadgeText: 'Season 3 In Production',
    nextSeasonNumber: 3,
    nextSeasonReleaseDate: '2026-10-18',
    nextSeasonDaysLeft: 61,
    renewalNewsSummary: 'HBO renewed House of the Dragon for Seasons 3 and 4, confirming Season 4 will be the final chapter.',
    productionNotes: 'Ryan Condal filming major dragon battles including the Battle of the Gullet.',
    creator: 'Ryan J. Condal & George R.R. Martin',
    network: 'HBO / Max',
    cast: [
      { name: 'Emma D\'Arcy', role: 'Rhaenyra Targaryen' },
      { name: 'Matt Smith', role: 'Daemon Targaryen' },
      { name: 'Olivia Cooke', role: 'Alicent Hightower' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 10, releaseDate: '2022-08-21', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 8, releaseDate: '2024-06-16', status: 'released' },
      { seasonNumber: 3, title: 'Season 3', episodeCount: 8, releaseDate: '2026-10-18', status: 'upcoming', countdownDays: 61 }
    ]
  },
  {
    id: 'the-bear',
    title: 'The Bear',
    tagline: 'Every second counts.',
    synopsis: 'A young chef from the fine dining world returns to Chicago to run his family\'s sandwich shop after a heartbreaking death.',
    posterUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1600&auto=format&fit=crop&q=80',
    providers: ['hulu', 'disney'],
    primaryProvider: 'hulu',
    genres: ['Comedy-Drama', 'Culinary', 'Psychological'],
    rating: 8.6,
    ratingCount: '280K+',
    contentRating: 'TV-MA',
    firstAirYear: 2022,
    decade: '2020s',
    totalSeasons: 4,
    totalEpisodes: 38,
    status: 'Returning Series',
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: true,
    renewalState: 'renewed',
    renewalBadgeText: 'Renewed for Season 5',
    nextSeasonNumber: 5,
    nextSeasonReleaseDate: '2027-06-25',
    nextSeasonDaysLeft: 310,
    renewalNewsSummary: 'FX and Hulu renewed the Emmy-winning series for Season 5 following Season 4 premiere.',
    productionNotes: 'Christopher Storer continues leading writer room in Chicago.',
    creator: 'Christopher Storer',
    network: 'FX on Hulu / Disney+',
    cast: [
      { name: 'Jeremy Allen White', role: 'Carmen "Carmy" Berzatto' },
      { name: 'Ayo Edebiri', role: 'Sydney Adamu' },
      { name: 'Ebon Moss-Bachrach', role: 'Richard "Richie" Jerimovich' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 8, releaseDate: '2022-06-23', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 10, releaseDate: '2023-06-22', status: 'released' },
      { seasonNumber: 3, title: 'Season 3', episodeCount: 10, releaseDate: '2024-06-26', status: 'released' },
      { seasonNumber: 4, title: 'Season 4', episodeCount: 10, releaseDate: '2025-06-25', status: 'released' },
      { seasonNumber: 5, title: 'Season 5', episodeCount: 10, releaseDate: '2027-06-25', status: 'upcoming', countdownDays: 310 }
    ]
  },
  {
    id: 'fallout',
    title: 'Fallout',
    tagline: 'The end was just the beginning.',
    synopsis: 'In a future, post-apocalyptic Los Angeles brought about by nuclear decimation, citizens must live in underground bunkers to protect themselves from radiation, mutants and bandits.',
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80',
    providers: ['prime'],
    primaryProvider: 'prime',
    genres: ['Sci-Fi', 'Action', 'Post-Apocalyptic', 'Dark Comedy'],
    rating: 8.4,
    ratingCount: '250K+',
    contentRating: 'TV-MA',
    firstAirYear: 2024,
    decade: '2020s',
    totalSeasons: 2,
    totalEpisodes: 16,
    status: 'Returning Series',
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: true,
    renewalState: 'in_production',
    renewalBadgeText: 'Season 2 In Production (New Vegas)',
    nextSeasonNumber: 2,
    nextSeasonReleaseDate: '2026-12-10',
    nextSeasonDaysLeft: 114,
    renewalNewsSummary: 'Prime Video fast-tracked Season 2 set in New Vegas, introducing Deathclaws and Robert House lore.',
    productionNotes: 'Jonathan Nolan and Lisa Joy directing episodes across California and Nevada.',
    creator: 'Graham Wagner & Geneva Robertson-Dworet',
    network: 'Prime Video',
    cast: [
      { name: 'Ella Purnell', role: 'Lucy MacLean' },
      { name: 'Walton Goggins', role: 'The Ghoul / Cooper Howard' },
      { name: 'Aaron Moten', role: 'Maximus' },
      { name: 'Kyle MacLachlan', role: 'Hank MacLean' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 8, releaseDate: '2024-04-10', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 8, releaseDate: '2026-12-10', status: 'upcoming', countdownDays: 114 }
    ]
  },
  {
    id: 'shogun',
    title: 'Shōgun',
    tagline: 'When two ambitious men from different worlds collide, an empire trembles.',
    synopsis: 'When a mysterious European ship is found marooned in a nearby fishing village, Lord Yoshii Toranaga discovers secrets that could tip the scales of power in feudal Japan.',
    posterUrl: 'https://images.unsplash.com/photo-1528164344705-475426879c0d?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1600&auto=format&fit=crop&q=80',
    providers: ['hulu', 'disney'],
    primaryProvider: 'hulu',
    genres: ['Historical Drama', 'War', 'Adventure', 'Political'],
    rating: 8.8,
    ratingCount: '210K+',
    contentRating: 'TV-MA',
    firstAirYear: 2024,
    decade: '2020s',
    totalSeasons: 3,
    totalEpisodes: 20,
    status: 'Returning Series',
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: true,
    renewalState: 'renewed',
    renewalBadgeText: 'Renewed for Seasons 2 & 3',
    nextSeasonNumber: 2,
    nextSeasonReleaseDate: '2027-02-20',
    nextSeasonDaysLeft: 185,
    renewalNewsSummary: 'Following a record 18 Emmy wins, FX and estate of James Clavell greenlit two brand new original seasons.',
    productionNotes: 'Hiroyuki Sanada returning as Lord Toranaga and executive producer.',
    creator: 'Rachel Kondo & Justin Marks',
    network: 'FX / Hulu / Disney+',
    cast: [
      { name: 'Hiroyuki Sanada', role: 'Lord Yoshii Toranaga' },
      { name: 'Cosmo Jarvis', role: 'John Blackthorne' },
      { name: 'Anna Sawai', role: 'Toda Mariko' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 10, releaseDate: '2024-02-27', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 10, releaseDate: '2027-02-20', status: 'upcoming', countdownDays: 185 }
    ]
  },
  {
    id: 'slow-horses',
    title: 'Slow Horses',
    tagline: 'MI5\'s dumping ground for disgraced agents.',
    synopsis: 'A dysfunctional team of MI5 agents and their obnoxious boss, the notorious Jackson Lamb, navigate the espionage world to defend England from sinister forces.',
    posterUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&auto=format&fit=crop&q=80',
    providers: ['appletv'],
    primaryProvider: 'appletv',
    genres: ['Espionage', 'Dark Comedy', 'Thriller', 'Mystery'],
    rating: 8.3,
    ratingCount: '110K+',
    contentRating: 'TV-MA',
    firstAirYear: 2022,
    decade: '2020s',
    totalSeasons: 6,
    totalEpisodes: 36,
    status: 'Returning Series',
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: true,
    renewalState: 'season_upcoming',
    renewalBadgeText: 'Season 5 Premiering Soon',
    nextSeasonNumber: 5,
    nextSeasonReleaseDate: '2026-09-04',
    nextSeasonDaysLeft: 17,
    renewalNewsSummary: 'Apple TV+ has pre-renewed Slow Horses through Season 6 adapting Mick Herron\'s "Joe Country".',
    productionNotes: 'Gary Oldman continues to lead the Slough House misfits.',
    creator: 'Will Smith (showrunner)',
    network: 'Apple TV+',
    cast: [
      { name: 'Gary Oldman', role: 'Jackson Lamb' },
      { name: 'Jack Lowden', role: 'River Cartwright' },
      { name: 'Kristin Scott Thomas', role: 'Diana Taverner' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 6, releaseDate: '2022-04-01', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 6, releaseDate: '2022-12-02', status: 'released' },
      { seasonNumber: 3, title: 'Season 3', episodeCount: 6, releaseDate: '2023-11-29', status: 'released' },
      { seasonNumber: 4, title: 'Season 4', episodeCount: 6, releaseDate: '2024-09-04', status: 'released' },
      { seasonNumber: 5, title: 'Season 5', episodeCount: 6, releaseDate: '2026-09-04', status: 'upcoming', countdownDays: 17 }
    ]
  },
  {
    id: 'the-white-lotus',
    title: 'The White Lotus',
    tagline: 'Paradise has a dark side.',
    synopsis: 'A sharp social satire following the exploits of various employees and guests at an exclusive Hawaiian resort over the span of a week, evolving into a global anthology in Sicily and Thailand.',
    posterUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&auto=format&fit=crop&q=80',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Satire', 'Dark Comedy', 'Drama', 'Mystery'],
    rating: 8.0,
    ratingCount: '230K+',
    contentRating: 'TV-MA',
    firstAirYear: 2021,
    decade: '2020s',
    totalSeasons: 3,
    totalEpisodes: 20,
    status: 'Returning Series',
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: true,
    renewalState: 'season_upcoming',
    renewalBadgeText: 'Season 3 (Thailand) Upcoming',
    nextSeasonNumber: 3,
    nextSeasonReleaseDate: '2026-10-05',
    nextSeasonDaysLeft: 48,
    renewalNewsSummary: 'Season 3 moves to a luxury wellness resort in Thailand examining spirituality and Eastern philosophy.',
    productionNotes: 'Mike White directs star-studded cast including Carrie Coon, Walton Goggins, and BLACKPINK’s Lisa.',
    creator: 'Mike White',
    network: 'HBO / Max',
    cast: [
      { name: 'Carrie Coon', role: 'Guest' },
      { name: 'Walton Goggins', role: 'Guest' },
      { name: 'Lalisa Manobal', role: 'Mook' },
      { name: 'Leslie Bibb', role: 'Guest' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1: Hawaii', episodeCount: 6, releaseDate: '2021-07-11', status: 'released' },
      { seasonNumber: 2, title: 'Season 2: Sicily', episodeCount: 7, releaseDate: '2022-10-30', status: 'released' },
      { seasonNumber: 3, title: 'Season 3: Thailand', episodeCount: 7, releaseDate: '2026-10-05', status: 'upcoming', countdownDays: 48 }
    ]
  },
  {
    id: 'wednesday',
    title: 'Wednesday',
    tagline: 'Snap snap.',
    synopsis: 'Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.',
    posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    providers: ['netflix'],
    primaryProvider: 'netflix',
    genres: ['Fantasy', 'Comedy Horror', 'Mystery', 'Teen Drama'],
    rating: 8.1,
    ratingCount: '390K+',
    contentRating: 'TV-14',
    firstAirYear: 2022,
    decade: '2020s',
    totalSeasons: 2,
    totalEpisodes: 16,
    status: 'Returning Series',
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: true,
    renewalState: 'in_production',
    renewalBadgeText: 'Season 2 In Production (Ireland)',
    nextSeasonNumber: 2,
    nextSeasonReleaseDate: '2026-10-24',
    nextSeasonDaysLeft: 67,
    renewalNewsSummary: 'Season 2 is leaning into more horror and action, introducing Steve Buscemi and Christopher Lloyd.',
    productionNotes: 'Filming in Wicklow, Ireland with Tim Burton directing premiering episodes.',
    creator: 'Alfred Gough & Miles Millar',
    network: 'Netflix',
    cast: [
      { name: 'Jenna Ortega', role: 'Wednesday Addams' },
      { name: 'Emma Myers', role: 'Enid Sinclair' },
      { name: 'Steve Buscemi', role: 'Principal Barry Dort' },
      { name: 'Catherine Zeta-Jones', role: 'Morticia Addams' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 8, releaseDate: '2022-11-23', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 8, releaseDate: '2026-10-24', status: 'upcoming', countdownDays: 67 }
    ]
  },

  // --- UPCOMING RELEASES & PREMIERES (NEW SHOWS & SEASONS) ---
  {
    id: 'silo',
    title: 'Silo',
    tagline: 'The truth will surface.',
    synopsis: 'In a ruined and toxic future, thousands live in a giant silo deep underground. After its sheriff breaks a cardinal rule and residents die mysteriously, engineer Juliette starts uncovering shocking secrets.',
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&auto=format&fit=crop&q=80',
    providers: ['appletv'],
    primaryProvider: 'appletv',
    genres: ['Sci-Fi', 'Dystopian', 'Mystery', 'Drama'],
    rating: 8.1,
    ratingCount: '140K+',
    contentRating: 'TV-MA',
    firstAirYear: 2023,
    decade: '2020s',
    totalSeasons: 3,
    totalEpisodes: 30,
    status: 'Returning Series',
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: true,
    renewalState: 'renewed',
    renewalBadgeText: 'Renewed for Season 3 & 4 (Final)',
    nextSeasonNumber: 3,
    nextSeasonReleaseDate: '2026-11-20',
    nextSeasonDaysLeft: 94,
    renewalNewsSummary: 'Apple TV+ announced Seasons 3 and 4 will be filmed back-to-back to complete Hugh Howey’s Wool trilogy.',
    productionNotes: 'Rebecca Ferguson executive produces alongside showrunner Graham Yost.',
    creator: 'Graham Yost',
    network: 'Apple TV+',
    cast: [
      { name: 'Rebecca Ferguson', role: 'Juliette Nichols' },
      { name: 'Common', role: 'Robert Sims' },
      { name: 'Tim Robbins', role: 'Bernard Holland' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 10, releaseDate: '2023-05-05', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 10, releaseDate: '2024-11-15', status: 'released' },
      { seasonNumber: 3, title: 'Season 3', episodeCount: 10, releaseDate: '2026-11-20', status: 'upcoming', countdownDays: 94 }
    ]
  },
  {
    id: 'the-boys',
    title: 'The Boys',
    tagline: 'Never meet your heroes.',
    synopsis: 'A fun and irreverent take on what happens when superheroes—who are as popular as celebrities, as influential as politicians, and as revered as gods—abuse their superpowers rather than use them for good.',
    posterUrl: 'https://images.unsplash.com/photo-1563089145-599997674d42?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1600&auto=format&fit=crop&q=80',
    providers: ['prime'],
    primaryProvider: 'prime',
    genres: ['Action', 'Satire', 'Superhero', 'Black Comedy'],
    rating: 8.7,
    ratingCount: '690K+',
    contentRating: 'TV-MA',
    firstAirYear: 2019,
    decade: '2010s',
    totalSeasons: 5,
    totalEpisodes: 40,
    status: 'Returning Series',
    isNowPlaying: false,
    isUpcoming: true,
    isClassic: false,
    hasNewSeasonAlert: true,
    renewalState: 'final_season_upcoming',
    renewalBadgeText: 'Final Season 5 (Series Finale)',
    nextSeasonNumber: 5,
    nextSeasonReleaseDate: '2026-10-30',
    nextSeasonDaysLeft: 73,
    renewalNewsSummary: 'Eric Kripke confirmed Season 5 is the final, all-out showdown between Billy Butcher and Homelander.',
    productionNotes: 'Filming in Toronto with Jared Padalecki joining the cast in a secret guest role.',
    creator: 'Eric Kripke',
    network: 'Prime Video',
    cast: [
      { name: 'Karl Urban', role: 'Billy Butcher' },
      { name: 'Antony Starr', role: 'Homelander' },
      { name: 'Jack Quaid', role: 'Hughie Campbell' },
      { name: 'Erin Moriarty', role: 'Annie January / Starlight' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 8, releaseDate: '2019-07-26', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 8, releaseDate: '2020-09-04', status: 'released' },
      { seasonNumber: 3, title: 'Season 3', episodeCount: 8, releaseDate: '2022-06-03', status: 'released' },
      { seasonNumber: 4, title: 'Season 4', episodeCount: 8, releaseDate: '2024-06-13', status: 'released' },
      { seasonNumber: 5, title: 'Season 5 (Final)', episodeCount: 8, releaseDate: '2026-10-30', status: 'upcoming', countdownDays: 73 }
    ]
  },
  {
    id: 'andor',
    title: 'Star Wars: Andor',
    tagline: 'The revolution begins with a spark.',
    synopsis: 'In an era filled with danger, deception and intrigue, Cassian will embark on the path that is destined to turn him into a rebel hero who will challenge the tyrannical Galactic Empire.',
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80',
    providers: ['disney'],
    primaryProvider: 'disney',
    genres: ['Sci-Fi', 'Political Thriller', 'Action', 'Spy'],
    rating: 8.4,
    ratingCount: '195K+',
    contentRating: 'TV-14',
    firstAirYear: 2022,
    decade: '2020s',
    totalSeasons: 2,
    totalEpisodes: 24,
    status: 'Returning Series',
    isNowPlaying: false,
    isUpcoming: true,
    isClassic: false,
    hasNewSeasonAlert: true,
    renewalState: 'final_season_upcoming',
    renewalBadgeText: 'Final Season 2 Premiering Soon',
    nextSeasonNumber: 2,
    nextSeasonReleaseDate: '2026-09-12',
    nextSeasonDaysLeft: 25,
    renewalNewsSummary: 'Season 2 covers the four years leading up to Rogue One in three-episode narrative blocks.',
    productionNotes: 'Tony Gilroy wraps the critically acclaimed Lucasfilm prequel saga.',
    creator: 'Tony Gilroy',
    network: 'Disney+',
    cast: [
      { name: 'Diego Luna', role: 'Cassian Andor' },
      { name: 'Stellan Skarsgård', role: 'Luthen Rael' },
      { name: 'Genevieve O\'Reilly', role: 'Mon Mothma' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 12, releaseDate: '2022-09-21', status: 'released' },
      { seasonNumber: 2, title: 'Season 2 (Final)', episodeCount: 12, releaseDate: '2026-09-12', status: 'upcoming', countdownDays: 25 }
    ]
  },
  {
    id: 'yellowjackets',
    title: 'Yellowjackets',
    tagline: 'Past is never past.',
    synopsis: 'A wildly talented high school girl soccer team becomes the (un)lucky survivors of a plane crash deep in the Ontario wilderness.',
    posterUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1600&auto=format&fit=crop&q=80',
    providers: ['paramount'],
    primaryProvider: 'paramount',
    genres: ['Psychological Horror', 'Mystery', 'Drama', 'Survival'],
    rating: 7.8,
    ratingCount: '98K+',
    contentRating: 'TV-MA',
    firstAirYear: 2021,
    decade: '2020s',
    totalSeasons: 3,
    totalEpisodes: 29,
    status: 'Returning Series',
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: true,
    renewalState: 'renewed',
    renewalBadgeText: 'Season 3 Ready • Season 4 Renewed',
    nextSeasonNumber: 3,
    nextSeasonReleaseDate: '2026-09-28',
    nextSeasonDaysLeft: 41,
    renewalNewsSummary: 'Showtime / Paramount+ renewed Yellowjackets for Season 4 ahead of the Season 3 broadcast.',
    productionNotes: 'Hilary Swank joins the adult timeline cast.',
    creator: 'Ashley Lyle & Bart Nickerson',
    network: 'Showtime / Paramount+',
    cast: [
      { name: 'Melanie Lynskey', role: 'Shauna Sadecki' },
      { name: 'Christina Ricci', role: 'Misty Quigley' },
      { name: 'Tawny Cypress', role: 'Taissa Turner' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 10, releaseDate: '2021-11-14', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 9, releaseDate: '2023-03-26', status: 'released' },
      { seasonNumber: 3, title: 'Season 3', episodeCount: 10, releaseDate: '2026-09-28', status: 'upcoming', countdownDays: 41 }
    ]
  },

  // --- CLASSIC & OLDER ARCHIVE SERIES (70s, 80s, 90s, 2000s, 2010s) ---
  {
    id: 'the-sopranos',
    title: 'The Sopranos',
    tagline: 'If one family doesn\'t kill him, the other family will.',
    synopsis: "New Jersey mob boss Tony Soprano deals with personal and professional issues in his home and business life that's affecting his mental state, leading him to seek professional psychiatric counseling.",
    posterUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&auto=format&fit=crop&q=80',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Crime Drama', 'Mob', 'Psychological', 'Masterpiece'],
    rating: 9.2,
    ratingCount: '460K+',
    contentRating: 'TV-MA',
    firstAirYear: 1999,
    lastAirYear: 2007,
    decade: '90s',
    totalSeasons: 6,
    totalEpisodes: 86,
    status: 'Ended',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    renewalState: 'concluded',
    renewalBadgeText: 'Classic • Complete (6 Seasons)',
    renewalNewsSummary: 'Complete legendary HBO series. Celebrated 25th anniversary with 4K HDR remaster on Max.',
    creator: 'David Chase',
    network: 'HBO / Max',
    cast: [
      { name: 'James Gandolfini', role: 'Tony Soprano' },
      { name: 'Lorraine Bracco', role: 'Dr. Jennifer Melfi' },
      { name: 'Edie Falco', role: 'Carmela Soprano' },
      { name: 'Michael Imperioli', role: 'Christopher Moltisanti' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 13, releaseDate: '1999-01-10', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 13, releaseDate: '2000-01-16', status: 'released' },
      { seasonNumber: 3, title: 'Season 3', episodeCount: 13, releaseDate: '2001-03-04', status: 'released' },
      { seasonNumber: 4, title: 'Season 4', episodeCount: 13, releaseDate: '2002-09-15', status: 'released' },
      { seasonNumber: 5, title: 'Season 5', episodeCount: 13, releaseDate: '2004-03-07', status: 'released' },
      { seasonNumber: 6, title: 'Season 6 (Part I & II)', episodeCount: 21, releaseDate: '2006-03-12', status: 'released' }
    ]
  },
  {
    id: 'breaking-bad',
    title: 'Breaking Bad',
    tagline: 'Change the equation.',
    synopsis: 'A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student in order to secure his family\'s financial future.',
    posterUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1600&auto=format&fit=crop&q=80',
    providers: ['netflix'],
    primaryProvider: 'netflix',
    genres: ['Crime Thriller', 'Suspense', 'Drama', 'Tragedy'],
    rating: 9.5,
    ratingCount: '2.1M+',
    contentRating: 'TV-MA',
    firstAirYear: 2008,
    lastAirYear: 2013,
    decade: '2000s',
    totalSeasons: 5,
    totalEpisodes: 62,
    status: 'Ended',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    renewalState: 'concluded',
    renewalBadgeText: 'Classic • Complete (5 Seasons)',
    renewalNewsSummary: 'Highest-rated TV drama in history. Full series streaming globally on Netflix.',
    creator: 'Vince Gilligan',
    network: 'AMC / Netflix',
    cast: [
      { name: 'Bryan Cranston', role: 'Walter White' },
      { name: 'Aaron Paul', role: 'Jesse Pinkman' },
      { name: 'Anna Gunn', role: 'Skyler White' },
      { name: 'Dean Norris', role: 'Hank Schrader' },
      { name: 'Giancarlo Esposito', role: 'Gus Fring' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 7, releaseDate: '2008-01-20', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 13, releaseDate: '2009-03-08', status: 'released' },
      { seasonNumber: 3, title: 'Season 3', episodeCount: 13, releaseDate: '2010-03-21', status: 'released' },
      { seasonNumber: 4, title: 'Season 4', episodeCount: 13, releaseDate: '2011-07-17', status: 'released' },
      { seasonNumber: 5, title: 'Season 5', episodeCount: 16, releaseDate: '2012-07-15', status: 'released' }
    ]
  },
  {
    id: 'the-wire',
    title: 'The Wire',
    tagline: 'Listen carefully.',
    synopsis: 'Told from the points of view of both the police and their targets, the series captures a world where easy distinctions between good and evil are corrupted by institutional failure.',
    posterUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1600&auto=format&fit=crop&q=80',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Crime', 'Urban Drama', 'Political', 'Realism'],
    rating: 9.3,
    ratingCount: '380K+',
    contentRating: 'TV-MA',
    firstAirYear: 2002,
    lastAirYear: 2008,
    decade: '2000s',
    totalSeasons: 5,
    totalEpisodes: 60,
    status: 'Ended',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    renewalState: 'concluded',
    renewalBadgeText: 'Classic • Complete (5 Seasons)',
    renewalNewsSummary: 'Landmark socio-political drama examining drug trade, port unions, city hall, public schools, and journalism.',
    creator: 'David Simon',
    network: 'HBO / Max',
    cast: [
      { name: 'Dominic West', role: 'Jimmy McNulty' },
      { name: 'Idris Elba', role: 'Stringer Bell' },
      { name: 'Michael K. Williams', role: 'Omar Little' },
      { name: 'Wendell Pierce', role: 'Bunk Moreland' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1: The Drug Trade', episodeCount: 13, releaseDate: '2002-06-02', status: 'released' },
      { seasonNumber: 2, title: 'Season 2: The Docks', episodeCount: 12, releaseDate: '2003-06-01', status: 'released' },
      { seasonNumber: 3, title: 'Season 3: City Politics', episodeCount: 12, releaseDate: '2004-09-19', status: 'released' },
      { seasonNumber: 4, title: 'Season 4: The School System', episodeCount: 13, releaseDate: '2006-09-10', status: 'released' },
      { seasonNumber: 5, title: 'Season 5: The Print Media', episodeCount: 10, releaseDate: '2008-01-06', status: 'released' }
    ]
  },
  {
    id: 'the-twilight-zone',
    title: 'The Twilight Zone',
    tagline: 'You unlock this door with the key of imagination.',
    synopsis: 'Ordinary people find themselves in extraordinarily astounding situations, which they each try to solve in a remarkable manner.',
    posterUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    providers: ['paramount', 'prime'],
    primaryProvider: 'paramount',
    genres: ['Sci-Fi', 'Anthology', 'Psychological', 'Fantasy', 'Vintage'],
    rating: 9.1,
    ratingCount: '95K+',
    contentRating: 'TV-PG',
    firstAirYear: 1959,
    lastAirYear: 1964,
    decade: '70s', // classic vintage bucket
    totalSeasons: 5,
    totalEpisodes: 156,
    status: 'Ended',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    renewalState: 'concluded',
    renewalBadgeText: 'Vintage Pioneer (5 Seasons)',
    renewalNewsSummary: 'Rod Serling\'s timeless masterpiece anthologizing humanity, irony, and the cosmos.',
    creator: 'Rod Serling',
    network: 'CBS / Paramount+',
    cast: [
      { name: 'Rod Serling', role: 'Host / Narrator' },
      { name: 'Burgess Meredith', role: 'Various Roles' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 36, releaseDate: '1959-10-02', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 29, releaseDate: '1960-09-30', status: 'released' },
      { seasonNumber: 3, title: 'Season 3', episodeCount: 37, releaseDate: '1961-09-15', status: 'released' },
      { seasonNumber: 4, title: 'Season 4', episodeCount: 18, releaseDate: '1963-01-03', status: 'released' },
      { seasonNumber: 5, title: 'Season 5', episodeCount: 36, releaseDate: '1963-09-27', status: 'released' }
    ]
  },
  {
    id: 'twin-peaks',
    title: 'Twin Peaks',
    tagline: 'A town where everyone knows everyone and nothing is what it seems.',
    synopsis: 'An idiosyncratic FBI agent investigates the murder of a young woman in the even more idiosyncratic town of Twin Peaks.',
    posterUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1600&auto=format&fit=crop&q=80',
    providers: ['paramount', 'prime'],
    primaryProvider: 'paramount',
    genres: ['Surrealist Mystery', 'Crime', 'Drama', 'Cult Classic'],
    rating: 8.8,
    ratingCount: '220K+',
    contentRating: 'TV-MA',
    firstAirYear: 1990,
    lastAirYear: 2017,
    decade: '90s',
    totalSeasons: 3,
    totalEpisodes: 48,
    status: 'Ended',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    renewalState: 'concluded',
    renewalBadgeText: 'Cult Classic (3 Seasons)',
    renewalNewsSummary: 'David Lynch & Mark Frost\'s genre-defining surreal mystery, including 2017\'s The Return on Paramount+.',
    creator: 'David Lynch & Mark Frost',
    network: 'ABC / Showtime',
    cast: [
      { name: 'Kyle MacLachlan', role: 'Special Agent Dale Cooper' },
      { name: 'Michael Ontkean', role: 'Sheriff Harry S. Truman' },
      { name: 'Mädchen Amick', role: 'Shelly Johnson' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 8, releaseDate: '1990-04-08', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 22, releaseDate: '1990-09-30', status: 'released' },
      { seasonNumber: 3, title: 'Season 3: The Return', episodeCount: 18, releaseDate: '2017-05-21', status: 'released' }
    ]
  },
  {
    id: 'mad-men',
    title: 'Mad Men',
    tagline: 'Where the truth lies.',
    synopsis: 'A drama about one of New York\'s most prestigious ad agencies at the beginning of the 1960s, focusing on one of the firm\'s most mysterious but extremely talented ad executives, Donald Draper.',
    posterUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1600&auto=format&fit=crop&q=80',
    providers: ['prime', 'paramount'],
    primaryProvider: 'prime',
    genres: ['Period Drama', 'Psychological', 'Historical'],
    rating: 8.7,
    ratingCount: '270K+',
    contentRating: 'TV-14',
    firstAirYear: 2007,
    lastAirYear: 2015,
    decade: '2000s',
    totalSeasons: 7,
    totalEpisodes: 92,
    status: 'Ended',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    renewalState: 'concluded',
    renewalBadgeText: 'Classic • 4x Best Drama Winner',
    renewalNewsSummary: 'Winner of 16 Primetime Emmys, streaming in high definition on Prime Video and AMC+.',
    creator: 'Matthew Weiner',
    network: 'AMC',
    cast: [
      { name: 'Jon Hamm', role: 'Don Draper' },
      { name: 'Elisabeth Moss', role: 'Peggy Olson' },
      { name: 'Vincent Kartheiser', role: 'Pete Campbell' },
      { name: 'January Jones', role: 'Betty Draper' },
      { name: 'Christina Hendricks', role: 'Joan Holloway' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 13, releaseDate: '2007-07-19', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 13, releaseDate: '2008-07-27', status: 'released' },
      { seasonNumber: 3, title: 'Season 3', episodeCount: 13, releaseDate: '2009-08-16', status: 'released' },
      { seasonNumber: 4, title: 'Season 4', episodeCount: 13, releaseDate: '2010-07-25', status: 'released' },
      { seasonNumber: 5, title: 'Season 5', episodeCount: 13, releaseDate: '2012-03-25', status: 'released' },
      { seasonNumber: 6, title: 'Season 6', episodeCount: 13, releaseDate: '2013-04-07', status: 'released' },
      { seasonNumber: 7, title: 'Season 7 (Part 1 & 2)', episodeCount: 14, releaseDate: '2014-04-13', status: 'released' }
    ]
  },
  {
    id: 'succession',
    title: 'Succession',
    tagline: 'Make your move.',
    synopsis: 'The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their aging father steps down from the company.',
    posterUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1600&auto=format&fit=crop&q=80',
    providers: ['max'],
    primaryProvider: 'max',
    genres: ['Corporate Satire', 'Family Drama', 'Dark Comedy'],
    rating: 8.9,
    ratingCount: '340K+',
    contentRating: 'TV-MA',
    firstAirYear: 2018,
    lastAirYear: 2023,
    decade: '2010s',
    totalSeasons: 4,
    totalEpisodes: 39,
    status: 'Ended',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    renewalState: 'concluded',
    renewalBadgeText: 'Modern Classic (Complete)',
    renewalNewsSummary: 'Jesse Armstrong\'s critically hailed multi-Emmy masterpiece streaming entirely on Max.',
    creator: 'Jesse Armstrong',
    network: 'HBO / Max',
    cast: [
      { name: 'Brian Cox', role: 'Logan Roy' },
      { name: 'Jeremy Strong', role: 'Kendall Roy' },
      { name: 'Sarah Snook', role: 'Shiv Roy' },
      { name: 'Kieran Culkin', role: 'Roman Roy' },
      { name: 'Matthew Macfadyen', role: 'Tom Wambsgans' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 10, releaseDate: '2018-06-03', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 10, releaseDate: '2019-08-11', status: 'released' },
      { seasonNumber: 3, title: 'Season 3', episodeCount: 9, releaseDate: '2021-10-17', status: 'released' },
      { seasonNumber: 4, title: 'Season 4 (Final)', episodeCount: 10, releaseDate: '2023-03-26', status: 'released' }
    ]
  },
  {
    id: 'star-trek-tng',
    title: 'Star Trek: The Next Generation',
    tagline: 'To boldly go where no one has gone before.',
    synopsis: 'Set almost 100 years after Captain Kirk\'s five-year mission, a new generation of Starfleet officers sets off in the U.S.S. Enterprise-D on their own mission to explore miraculous new worlds.',
    posterUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=1600&auto=format&fit=crop&q=80',
    providers: ['paramount', 'netflix'],
    primaryProvider: 'paramount',
    genres: ['Sci-Fi', 'Space Exploration', 'Adventure', 'Utopian'],
    rating: 8.7,
    ratingCount: '135K+',
    contentRating: 'TV-PG',
    firstAirYear: 1987,
    lastAirYear: 1994,
    decade: '80s',
    totalSeasons: 7,
    totalEpisodes: 178,
    status: 'Ended',
    isNowPlaying: false,
    isUpcoming: false,
    isClassic: true,
    hasNewSeasonAlert: false,
    renewalState: 'concluded',
    renewalBadgeText: 'Sci-Fi Classic (7 Seasons)',
    renewalNewsSummary: 'Remastered in full 1080p HD, streaming on Paramount+ and Netflix.',
    creator: 'Gene Roddenberry',
    network: 'Syndication / Paramount+',
    cast: [
      { name: 'Patrick Stewart', role: 'Captain Jean-Luc Picard' },
      { name: 'Jonathan Frakes', role: 'Commander William Riker' },
      { name: 'Brent Spiner', role: 'Lt. Commander Data' },
      { name: 'LeVar Burton', role: 'Geordi La Forge' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 26, releaseDate: '1987-09-28', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 22, releaseDate: '1988-11-21', status: 'released' },
      { seasonNumber: 3, title: 'Season 3', episodeCount: 26, releaseDate: '1989-09-25', status: 'released' },
      { seasonNumber: 4, title: 'Season 4', episodeCount: 26, releaseDate: '1990-09-24', status: 'released' },
      { seasonNumber: 5, title: 'Season 5', episodeCount: 26, releaseDate: '1991-09-23', status: 'released' },
      { seasonNumber: 6, title: 'Season 6', episodeCount: 26, releaseDate: '1992-09-21', status: 'released' },
      { seasonNumber: 7, title: 'Season 7', episodeCount: 26, releaseDate: '1993-09-20', status: 'released' }
    ]
  },
  {
    id: 'only-murders-in-the-building',
    title: 'Only Murders in the Building',
    tagline: 'True crime is in their blood.',
    synopsis: 'Three strangers who share an obsession with true crime podcasts suddenly find themselves wrapped up in one when a gruesome death occurs inside their exclusive Upper West Side apartment building.',
    posterUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=1600&auto=format&fit=crop&q=80',
    providers: ['hulu', 'disney'],
    primaryProvider: 'hulu',
    genres: ['Mystery Comedy', 'Whodunnit', 'Crime'],
    rating: 8.1,
    ratingCount: '170K+',
    contentRating: 'TV-MA',
    firstAirYear: 2021,
    decade: '2020s',
    totalSeasons: 5,
    totalEpisodes: 50,
    status: 'Returning Series',
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: true,
    renewalState: 'season_upcoming',
    renewalBadgeText: 'Season 5 Premiering in 38 Days',
    nextSeasonNumber: 5,
    nextSeasonReleaseDate: '2026-09-25',
    nextSeasonDaysLeft: 38,
    renewalNewsSummary: 'Hulu greenlit Season 5 following the cliffhanger finale of Season 4.',
    productionNotes: 'Steve Martin, Martin Short, and Selena Gomez continue producing and starring.',
    creator: 'Steve Martin & John Hoffman',
    network: 'Hulu / Disney+',
    cast: [
      { name: 'Steve Martin', role: 'Charles-Haden Savage' },
      { name: 'Martin Short', role: 'Oliver Putnam' },
      { name: 'Selena Gomez', role: 'Mabel Mora' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 10, releaseDate: '2021-08-31', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 10, releaseDate: '2022-06-28', status: 'released' },
      { seasonNumber: 3, title: 'Season 3', episodeCount: 10, releaseDate: '2023-08-08', status: 'released' },
      { seasonNumber: 4, title: 'Season 4', episodeCount: 10, releaseDate: '2024-08-27', status: 'released' },
      { seasonNumber: 5, title: 'Season 5', episodeCount: 10, releaseDate: '2026-09-25', status: 'upcoming', countdownDays: 38 }
    ]
  },
  {
    id: 'ted-lasso',
    title: 'Ted Lasso',
    tagline: 'Kindness makes a comeback.',
    synopsis: 'An American college football coach is hired to manage a British soccer team, AFC Richmond. What he lacks in knowledge, he makes up for with optimism, biscuits, and heart.',
    posterUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&auto=format&fit=crop&q=80',
    backdropUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1600&auto=format&fit=crop&q=80',
    providers: ['appletv'],
    primaryProvider: 'appletv',
    genres: ['Sports Comedy', 'Feel-Good', 'Drama'],
    rating: 8.8,
    ratingCount: '340K+',
    contentRating: 'TV-MA',
    firstAirYear: 2020,
    decade: '2020s',
    totalSeasons: 4,
    totalEpisodes: 46,
    status: 'Returning Series',
    isNowPlaying: false,
    isUpcoming: true,
    isClassic: false,
    hasNewSeasonAlert: true,
    renewalState: 'in_production',
    renewalBadgeText: 'Season 4 In Pre-Production (Greenlit!)',
    nextSeasonNumber: 4,
    nextSeasonReleaseDate: '2027-04-10',
    nextSeasonDaysLeft: 235,
    renewalNewsSummary: 'Warner Bros. and Apple TV+ officially picked up actor options for Season 4 focusing on AFC Richmond women\'s team / new league.',
    productionNotes: 'Jason Sudeikis and Brett Goldstein developing new story arcs.',
    creator: 'Jason Sudeikis, Bill Lawrence, Brendan Hunt, Joe Kelly',
    network: 'Apple TV+',
    cast: [
      { name: 'Jason Sudeikis', role: 'Ted Lasso' },
      { name: 'Hannah Waddingham', role: 'Rebecca Welton' },
      { name: 'Brett Goldstein', role: 'Roy Kent' },
      { name: 'Juno Temple', role: 'Keeley Jones' }
    ],
    seasons: [
      { seasonNumber: 1, title: 'Season 1', episodeCount: 10, releaseDate: '2020-08-14', status: 'released' },
      { seasonNumber: 2, title: 'Season 2', episodeCount: 12, releaseDate: '2021-07-23', status: 'released' },
      { seasonNumber: 3, title: 'Season 3', episodeCount: 12, releaseDate: '2023-03-15', status: 'released' },
      { seasonNumber: 4, title: 'Season 4', episodeCount: 12, releaseDate: '2027-04-10', status: 'upcoming', countdownDays: 235 }
    ]
  }
];
