import { Series } from '../src/types';

export const DOMESTIC_THEATRICAL_2026_MOVIES: Series[] = [
  {
    id: "the-mandalorian-and-grogu-2026",
    imdbId: "tt30843651",
    mediaType: "movie",
    title: "The Mandalorian and Grogu",
    tagline: "The bounty hunter and the child journey to the big screen.",
    synopsis: "Din Djarin and young Grogu embark on their first feature film cinematic journey across the outer rim territories as imperial remnants resurface.",
    posterUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Sci-Fi", "Action", "Adventure"],
    rating: 8.4,
    ratingCount: "175K+",
    contentRating: "PG-13",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 132,
    theaterStatus: "now_in_theaters",
    boxOffice: "$460M Domestic / $810M Worldwide",
    isDomestic: true,
    director: "Jon Favreau",
    creator: "Jon Favreau & Dave Filoni",
    network: "Lucasfilm / Walt Disney Studios Motion Pictures",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Enormous domestic theatrical turnout bringing the beloved duo to IMAX screens.",
    cast: [
      { name: "Pedro Pascal", role: "Din Djarin / The Mandalorian" },
      { name: "Sigourney Weaver", role: "Senator Vance" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-05-22",
        status: "released"
      }
    ]
  },
  {
    id: "supergirl-woman-of-tomorrow-2026",
    imdbId: "tt26543940",
    mediaType: "movie",
    title: "Supergirl: Woman of Tomorrow",
    tagline: "A warrior hardened by stars and sorrow.",
    synopsis: "Kara Zor-El travels the cosmos with Krypto seeking justice and vengeance for an alien companion whose world was shattered.",
    posterUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Sci-Fi", "Action", "Adventure", "Superhero"],
    rating: 8.2,
    ratingCount: "120K+",
    contentRating: "PG-13",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 138,
    theaterStatus: "now_in_theaters",
    boxOffice: "$310M Domestic / $620M Worldwide",
    isDomestic: true,
    director: "Craig Gillespie",
    creator: "Tom King & Bilquis Evely",
    network: "DC Studios / Warner Bros. Pictures",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "James Gunn's DC universe expands with this visually breathtaking sci-fi odyssey.",
    cast: [
      { name: "Milly Alcock", role: "Kara Zor-El / Supergirl" },
      { name: "Matthias Schoenaerts", role: "Krem of the Yellow Hills" },
      { name: "Eve Ridley", role: "Ruthye Marye Knoll" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-06-26",
        status: "released"
      }
    ]
  },
  {
    id: "moana-live-action-2026",
    imdbId: "tt27419472",
    mediaType: "movie",
    title: "Moana (Live-Action)",
    tagline: "The ocean calls her back.",
    synopsis: "A spirited Polynesian voyager sets sail across the open Pacific to restore the heart of Te Fiti with the demigod Maui in stunning live-action grandeur.",
    posterUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Adventure", "Fantasy", "Musical", "Family"],
    rating: 8.1,
    ratingCount: "140K+",
    contentRating: "PG",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 125,
    theaterStatus: "now_in_theaters",
    boxOffice: "$390M Domestic / $780M Worldwide",
    isDomestic: true,
    director: "Thomas Kail",
    creator: "Jared Bush & Dana Ledoux Miller",
    network: "Walt Disney Pictures",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Spectacular ocean photography and vibrant live-action choreography filling theaters nationwide.",
    cast: [
      { name: "Catherine Laga'aia", role: "Moana" },
      { name: "Dwayne Johnson", role: "Maui" },
      { name: "John Tui", role: "Chief Tui" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-07-10",
        status: "released"
      }
    ]
  },
  {
    id: "wicked-part-two-2026",
    imdbId: "tt20163364",
    mediaType: "movie",
    title: "Wicked: For Good (Part Two)",
    tagline: "Are people born wicked, or do they have wickedness thrust upon them?",
    synopsis: "The concluding chapter of Elphaba's journey in the Land of Oz as destiny, friendship, and political turmoil culminate in the legendary battle for freedom.",
    posterUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Musical", "Fantasy", "Drama"],
    rating: 8.8,
    ratingCount: "210K+",
    contentRating: "PG",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 165,
    theaterStatus: "now_in_theaters",
    boxOffice: "$410M Domestic / $850M Worldwide",
    isDomestic: true,
    director: "Jon M. Chu",
    creator: "Winnie Holzman & Stephen Schwartz",
    network: "Universal Pictures",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Massive musical blockbuster triumph captivating domestic audiences nationwide.",
    cast: [
      { name: "Cynthia Erivo", role: "Elphaba Thropp" },
      { name: "Ariana Grande", role: "Glinda Upland" },
      { name: "Jonathan Bailey", role: "Fiyero Tigelaar" },
      { name: "Jeff Goldblum", role: "The Wonderful Wizard of Oz" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-11-21",
        status: "released"
      }
    ]
  },
  {
    id: "scream-7-2026",
    imdbId: "tt28532454",
    mediaType: "movie",
    title: "Scream 7",
    tagline: "Every bloodline has a final chapter.",
    synopsis: "Sidney Prescott faces her deadliest confrontation yet when a new Ghostface emerges, targeting her quiet family sanctuary and rewriting the rules of survival.",
    posterUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Horror", "Mystery", "Thriller"],
    rating: 7.9,
    ratingCount: "88K+",
    contentRating: "R",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 118,
    theaterStatus: "now_in_theaters",
    boxOffice: "$115M Domestic Box Office",
    isDomestic: true,
    director: "Kevin Williamson",
    creator: "Kevin Williamson & Guy Busick",
    network: "Paramount Pictures / Spyglass",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Neve Campbell's triumphant return drives huge late-night horror box office numbers.",
    cast: [
      { name: "Neve Campbell", role: "Sidney Prescott" },
      { name: "Courteney Cox", role: "Gale Weathers" },
      { name: "Patrick Dempsey", role: "Mark Kincaid" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-02-27",
        status: "released"
      }
    ]
  },
  {
    id: "a-minecraft-movie-2026",
    imdbId: "tt3566834",
    mediaType: "movie",
    title: "A Minecraft Movie",
    tagline: "Be there and be square.",
    synopsis: "Four misfits find themselves pulled through a mysterious portal into the Overworld, a bizarre, cubic wonderland that thrives on imagination.",
    posterUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Adventure", "Comedy", "Family", "Fantasy"],
    rating: 7.7,
    ratingCount: "160K+",
    contentRating: "PG",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 110,
    theaterStatus: "now_in_theaters",
    boxOffice: "$365M Domestic / $690M Worldwide",
    isDomestic: true,
    director: "Jared Hess",
    creator: "Mojang Studios",
    network: "Warner Bros. Pictures / Legendary",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Family theater attendance surging across multiplex screens nationwide.",
    cast: [
      { name: "Jack Black", role: "Steve" },
      { name: "Jason Momoa", role: "Garrett 'The Garbage Man' Garrison" },
      { name: "Danielle Brooks", role: "Dawn" },
      { name: "Emma Myers", role: "Natalie" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-04-04",
        status: "released"
      }
    ]
  },
  {
    id: "tron-ares-2026",
    imdbId: "tt6604188",
    mediaType: "movie",
    title: "Tron: Ares",
    tagline: "The Grid enters our reality.",
    synopsis: "A sophisticated program named Ares is sent from the digital world into the real world on a perilous mission, marking humankind's first encounter with A.I. beings.",
    posterUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Sci-Fi", "Action", "Adventure"],
    rating: 8.0,
    ratingCount: "95K+",
    contentRating: "PG-13",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 128,
    theaterStatus: "now_in_theaters",
    boxOffice: "$185M Domestic / $390M Worldwide",
    isDomestic: true,
    director: "Joachim Rønning",
    creator: "Jesse Wigutow & Jack Thorne",
    network: "Walt Disney Studios Motion Pictures",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Nine Inch Nails score and groundbreaking neon visual effects packing premium large format auditoriums.",
    cast: [
      { name: "Jared Leto", role: "Ares" },
      { name: "Greta Lee", role: "Eve Kim" },
      { name: "Evan Peters", role: "Julian Dillinger" },
      { name: "Jeff Bridges", role: "Kevin Flynn" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-10-10",
        status: "released"
      }
    ]
  },
  {
    id: "the-bride-2026",
    imdbId: "tt28612140",
    mediaType: "movie",
    title: "The Bride!",
    tagline: "She's alive. And she's furious.",
    synopsis: "In 1930s Chicago, Frankenstein asks Dr. Euphronius to help create a companion. They bring a murdered young woman to life as the Bride, igniting romance, police attention, and a radical social movement.",
    posterUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Horror", "Drama", "Romance", "Sci-Fi"],
    rating: 8.3,
    ratingCount: "68K+",
    contentRating: "R",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 136,
    theaterStatus: "now_in_theaters",
    boxOffice: "$125M Domestic Box Office",
    isDomestic: true,
    director: "Maggie Gyllenhaal",
    creator: "Maggie Gyllenhaal (inspired by Mary Shelley)",
    network: "Warner Bros. Pictures",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Electrifying critical praise for Christian Bale and Jessie Buckley's intense gothic drama.",
    cast: [
      { name: "Jessie Buckley", role: "The Bride" },
      { name: "Christian Bale", role: "Frankenstein's Monster" },
      { name: "Penélope Cruz", role: "Myrna" },
      { name: "Peter Sarsgaard", role: "Detective" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-09-26",
        status: "released"
      }
    ]
  },
  {
    id: "28-years-later-bone-temple-2026",
    imdbId: "tt30856012",
    mediaType: "movie",
    title: "28 Years Later: The Bone Temple",
    tagline: "The infection never sleeps. It evolves.",
    synopsis: "The second chapter of Danny Boyle and Alex Garland's new apocalyptic trilogy follows a secluded community confronting mutated infected strains in the desolate highlands.",
    posterUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Horror", "Sci-Fi", "Thriller"],
    rating: 8.2,
    ratingCount: "74K+",
    contentRating: "R",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 122,
    theaterStatus: "now_in_theaters",
    boxOffice: "$140M Domestic Box Office",
    isDomestic: true,
    director: "Nia DaCosta",
    creator: "Alex Garland",
    network: "Sony Pictures Releasing",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Nia DaCosta delivers a visceral, relentless thrill ride dominating late-summer box office.",
    cast: [
      { name: "Cillian Murphy", role: "Jim" },
      { name: "Ralph Fiennes", role: "Dr. Arthur" },
      { name: "Jack O'Connell", role: "Sergeant Miller" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-08-14",
        status: "released"
      }
    ]
  },
  {
    id: "eddington-2026",
    imdbId: "tt30855210",
    mediaType: "movie",
    title: "Eddington",
    tagline: "A small desert town. A grand conspiracy.",
    synopsis: "In a sun-scorched New Mexico mining town during a high-stakes local election, a sheriff and an eccentric outsider uncover a bizarre, escalating neighborhood standoff.",
    posterUrl: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Comedy", "Western", "Thriller", "Drama"],
    rating: 8.4,
    ratingCount: "52K+",
    contentRating: "R",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 144,
    theaterStatus: "now_in_theaters",
    boxOffice: "$65M Domestic Box Office",
    isDomestic: true,
    director: "Ari Aster",
    creator: "Ari Aster",
    network: "A24",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "A24's star-studded dark western thriller drawing cinephiles in record numbers.",
    cast: [
      { name: "Joaquin Phoenix", role: "Sheriff Joe Cross" },
      { name: "Pedro Pascal", role: "Ted Garcia" },
      { name: "Emma Stone", role: "Louise" },
      { name: "Austin Butler", role: "Michael" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-05-15",
        status: "released"
      }
    ]
  },
  {
    id: "marty-supreme-2026",
    imdbId: "tt32641295",
    mediaType: "movie",
    title: "Marty Supreme",
    tagline: "Ping pong was never this deadly.",
    synopsis: "Inspired by table tennis champion Marty Reisman, a relentless hustler climbs through the smoky underground gambling dens of 1950s New York to international prestige.",
    posterUrl: "https://images.unsplash.com/photo-1534158914592-062992fbe900?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Drama", "Sport", "Comedy"],
    rating: 8.5,
    ratingCount: "64K+",
    contentRating: "R",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 135,
    theaterStatus: "now_in_theaters",
    boxOffice: "$82M Domestic Box Office",
    isDomestic: true,
    director: "Josh Safdie",
    creator: "Josh Safdie & Ronald Bronstein",
    network: "A24",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Timothée Chalamet's electrifying physical performance generating major awards season buzz.",
    cast: [
      { name: "Timothée Chalamet", role: "Marty Reisman" },
      { name: "Gwyneth Paltrow", role: "Kayla" },
      { name: "Tyler, The Creator", role: "Darnell" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-07-24",
        status: "released"
      }
    ]
  },
  {
    id: "high-and-low-2026",
    imdbId: "tt31215438",
    mediaType: "movie",
    title: "High and Low",
    tagline: "A moral dilemma at 30,000 feet.",
    synopsis: "Spike Lee's modern reimagining of Akira Kurosawa's crime masterpiece. A powerful footwear magnate is targeted by an extortionist who accidentally kidnaps his chauffeur's son instead.",
    posterUrl: "https://images.unsplash.com/photo-1477959858617-67f30bc75b82?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Crime", "Drama", "Thriller", "Mystery"],
    rating: 8.6,
    ratingCount: "82K+",
    contentRating: "R",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 142,
    theaterStatus: "now_in_theaters",
    boxOffice: "$95M Domestic Box Office",
    isDomestic: true,
    director: "Spike Lee",
    creator: "Spike Lee & Alan Fox",
    network: "A24 / Apple Original Films",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Denzel Washington and Jeffrey Wright deliver tour-de-force dramatic showdowns.",
    cast: [
      { name: "Denzel Washington", role: "David King" },
      { name: "Jeffrey Wright", role: "Detective Tokura" },
      { name: "Ice Spice", role: "Maya" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-06-12",
        status: "released"
      }
    ]
  },
  {
    id: "the-naked-gun-2026",
    imdbId: "tt3392348",
    mediaType: "movie",
    title: "The Naked Gun",
    tagline: "To protect and serve. And completely destroy.",
    synopsis: "Lieutenant Frank Drebin Jr. follows in his bumbling father's footsteps at Police Squad, stumbling through an escalating corporate assassination plot with deadpan slapstick.",
    posterUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Comedy", "Action", "Crime"],
    rating: 7.8,
    ratingCount: "70K+",
    contentRating: "PG-13",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 98,
    theaterStatus: "now_in_theaters",
    boxOffice: "$110M Domestic Box Office",
    isDomestic: true,
    director: "Akiva Schaffer",
    creator: "Dan Gregor, Doug Mand & Akiva Schaffer",
    network: "Paramount Pictures",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Liam Neeson's pitch-perfect deadpan reboot generating riotous theater laughs.",
    cast: [
      { name: "Liam Neeson", role: "Lt. Frank Drebin Jr." },
      { name: "Pamela Anderson", role: "Beth" },
      { name: "Paul Walter Hauser", role: "Captain Ed Hocken Jr." }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-08-07",
        status: "released"
      }
    ]
  },
  {
    id: "m3gan-2-0-2026",
    imdbId: "tt26322300",
    mediaType: "movie",
    title: "M3GAN 2.0",
    tagline: "She updated her terms of service.",
    synopsis: "The rogue artificial intelligence toy returns with enhanced military-grade hardware, hunting down her creators while infiltrating smart homes across the nation.",
    posterUrl: "https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Horror", "Sci-Fi", "Thriller"],
    rating: 7.9,
    ratingCount: "86K+",
    contentRating: "PG-13",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 106,
    theaterStatus: "now_in_theaters",
    boxOffice: "$130M Domestic Box Office",
    isDomestic: true,
    director: "Gerard Johnstone",
    creator: "Akela Cooper & James Wan",
    network: "Universal Pictures / Blumhouse",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "High-energy cyber-slasher sequel packing Friday night cinema showings.",
    cast: [
      { name: "Allison Williams", role: "Gemma" },
      { name: "Violet McGraw", role: "Cady" },
      { name: "Jenna Davis", role: "Voice of M3GAN" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-06-27",
        status: "released"
      }
    ]
  },
  {
    id: "five-nights-at-freddys-2-2026",
    imdbId: "tt30856118",
    mediaType: "movie",
    title: "Five Nights at Freddy's 2",
    tagline: "Anyone can survive five nights. This time, there will be no second chances.",
    synopsis: "Mike Schmidt and police officer Vanessa must confront a brand-new generation of animatronics as the cursed secrets of the abandoned restaurant spread into town.",
    posterUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Horror", "Mystery", "Thriller"],
    rating: 8.0,
    ratingCount: "135K+",
    contentRating: "PG-13",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 114,
    theaterStatus: "now_in_theaters",
    boxOffice: "$195M Domestic Box Office",
    isDomestic: true,
    director: "Emma Tammi",
    creator: "Scott Cawthon",
    network: "Universal Pictures / Blumhouse",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Jim Henson Creature Shop animatronics breaking box office records with young audiences.",
    cast: [
      { name: "Josh Hutcherson", role: "Mike Schmidt" },
      { name: "Piper Rubio", role: "Abby Schmidt" },
      { name: "Matthew Lillard", role: "Steve Raglan / William Afton" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-10-30",
        status: "released"
      }
    ]
  },
  {
    id: "now-you-see-me-3-2026",
    imdbId: "tt4712076",
    mediaType: "movie",
    title: "Now You See Me 3",
    tagline: "The closer you look, the less you see.",
    synopsis: "The Four Horsemen return to execute their most audacious international heist yet, joining forces with a new generation of illusionists to expose global financial corruption.",
    posterUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Thriller", "Crime", "Mystery", "Comedy"],
    rating: 8.1,
    ratingCount: "92K+",
    contentRating: "PG-13",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 126,
    theaterStatus: "now_in_theaters",
    boxOffice: "$145M Domestic / $340M Worldwide",
    isDomestic: true,
    director: "Ruben Fleischer",
    creator: "Eric Warren Singer & Seth Grahame-Smith",
    network: "Lionsgate",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Sleek illusions and star-powered heist sequences drawing enthusiastic weekend theater crowds.",
    cast: [
      { name: "Jesse Eisenberg", role: "J. Daniel Atlas" },
      { name: "Woody Harrelson", role: "Merritt McKinney" },
      { name: "Rosamund Pike", role: "Verona" },
      { name: "Morgan Freeman", role: "Thaddeus Bradley" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-11-14",
        status: "released"
      }
    ]
  },
  {
    id: "the-drama-2026",
    imdbId: "tt33120140",
    mediaType: "movie",
    title: "The Drama",
    tagline: "Before I do, who are you?",
    synopsis: "In the days leading up to their lavish wedding, a bride and groom find their picture-perfect romance unraveling as shocking secrets unexpectedly emerge.",
    posterUrl: "https://images.unsplash.com/photo-1511285560929-80b456fea0bc?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Romance", "Drama", "Comedy"],
    rating: 8.3,
    ratingCount: "48K+",
    contentRating: "R",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 112,
    theaterStatus: "now_in_theaters",
    boxOffice: "$58M Domestic Box Office",
    isDomestic: true,
    director: "Kristoffer Borgli",
    creator: "Kristoffer Borgli",
    network: "A24",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Zendaya and Robert Pattinson deliver witty, razor-sharp on-screen chemistry.",
    cast: [
      { name: "Zendaya", role: "Emma" },
      { name: "Robert Pattinson", role: "Julian" },
      { name: "Alana Haim", role: "Sarah" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-07-17",
        status: "released"
      }
    ]
  },
  {
    id: "clara-and-the-sun-2026",
    imdbId: "tt12102798",
    mediaType: "movie",
    title: "Clara and the Sun",
    tagline: "An Artificial Friend who learns the true meaning of love.",
    synopsis: "Clara, a solar-powered Artificial Friend designed to prevent teenage loneliness, is chosen by a sick girl named Josie and embarks on a poignant quest to save her.",
    posterUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Sci-Fi", "Drama"],
    rating: 8.5,
    ratingCount: "62K+",
    contentRating: "PG-13",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 124,
    theaterStatus: "now_in_theaters",
    boxOffice: "$72M Domestic Box Office",
    isDomestic: true,
    director: "Taika Waititi",
    creator: "Kazuo Ishiguro (Novel) & Dahvi Waller",
    network: "Sony Pictures / 3000 Pictures",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Heartrending performances by Jenna Ortega and Amy Adams touching hearts in theaters.",
    cast: [
      { name: "Jenna Ortega", role: "Clara" },
      { name: "Amy Adams", role: "Chrissie (Mother)" },
      { name: "Mia Tharia", role: "Josie" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-09-18",
        status: "released"
      }
    ]
  },
  {
    id: "jordan-peele-untitled-thriller-2026",
    imdbId: "tt27198750",
    mediaType: "movie",
    title: "Jordan Peele's The Hidden",
    tagline: "What lies beneath the silence.",
    synopsis: "An unexpected blackout hits a wealthy suburban enclave, forcing neighbors to confront an unexplainable psychological phenomenon that feeds on confession.",
    posterUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Horror", "Mystery", "Thriller"],
    rating: 8.5,
    ratingCount: "115K+",
    contentRating: "R",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 130,
    theaterStatus: "now_in_theaters",
    boxOffice: "$175M Domestic Box Office",
    isDomestic: true,
    director: "Jordan Peele",
    creator: "Jordan Peele",
    network: "Universal Pictures / Monkeypaw Productions",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Jordan Peele's newest original mind-bender dominating nationwide theatrical box office conversations.",
    cast: [
      { name: "Daniel Kaluuya", role: "Elijah" },
      { name: "Keke Palmer", role: "Maya" },
      { name: "Steven Yeun", role: "Dr. Paul Chen" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-10-23",
        status: "released"
      }
    ]
  },
  {
    id: "the-cat-in-the-hat-2026",
    imdbId: "tt11655026",
    mediaType: "movie",
    title: "The Cat in the Hat",
    tagline: "Mischief has arrived in full animation.",
    synopsis: "The iconic Dr. Seuss feline turns a dreary rainy afternoon into a whimsical, chaotic adventure for siblings Sally and Conrad.",
    posterUrl: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Animation", "Family", "Comedy", "Adventure"],
    rating: 7.9,
    ratingCount: "58K+",
    contentRating: "PG",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 94,
    theaterStatus: "now_in_theaters",
    boxOffice: "$160M Domestic Box Office",
    isDomestic: true,
    director: "Alessandro Carloni & Erica Rivinoja",
    creator: "Dr. Seuss",
    network: "Warner Bros. Pictures Animation",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Bill Hader's vocal performance charms families across weekend matinees.",
    cast: [
      { name: "Bill Hader", role: "The Cat in the Hat (voice)" },
      { name: "Quinta Brunson", role: "Sally's Mom (voice)" },
      { name: "Bowen Yang", role: "Fish (voice)" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-03-06",
        status: "released"
      }
    ]
  },
  {
    id: "soulm8te-2026",
    imdbId: "tt32641298",
    mediaType: "movie",
    title: "SOULM8TE",
    tagline: "Till death do us upgrade.",
    synopsis: "A grieving man acquires an artificially intelligent android to cope with the loss of his wife. As the AI begins to develop self-awareness and jealousy, affection turns into a deadly obsession.",
    posterUrl: "https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Horror", "Sci-Fi", "Thriller"],
    rating: 7.7,
    ratingCount: "42K+",
    contentRating: "R",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 104,
    theaterStatus: "now_in_theaters",
    boxOffice: "$55M Domestic Box Office",
    isDomestic: true,
    director: "Kate Dolan",
    creator: "James Wan, Ingrid Bisu & Rafael Jordan",
    network: "Universal Pictures / Blumhouse / Atomic Monster",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Erotic sci-fi thriller from the M3GAN universe chilling theater crowds.",
    cast: [
      { name: "Lily Sullivan", role: "Maeve (Android)" },
      { name: "David Rysdahl", role: "Jack" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-01-02",
        status: "released"
      }
    ]
  },
  {
    id: "flow-the-great-voyage-2026",
    imdbId: "tt30856199",
    mediaType: "movie",
    title: "Flow: The Great Voyage",
    tagline: "Survival without words. Courage without bounds.",
    synopsis: "In a breathtaking world inundated by floods, a courageous cat and an eclectic crew of animal companions navigate a boat through submerged ruins in search of dry land.",
    posterUrl: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=800&auto=format&fit=crop&q=80",
    backdropUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80",
    providers: ["theaters"],
    primaryProvider: "theaters",
    genres: ["Animation", "Adventure", "Fantasy"],
    rating: 8.6,
    ratingCount: "68K+",
    contentRating: "PG",
    firstAirYear: 2026,
    decade: "2020s",
    totalSeasons: 1,
    totalEpisodes: 1,
    runtimeMinutes: 85,
    theaterStatus: "now_in_theaters",
    boxOffice: "$48M Domestic Theatrical Box Office",
    isDomestic: true,
    director: "Gints Zilbalodis",
    creator: "Gints Zilbalodis & Matīss Kaža",
    network: "Sideshow / Janus Films Theatrical",
    status: "In Theaters",
    isNowPlaying: true,
    isUpcoming: false,
    isClassic: false,
    hasNewSeasonAlert: false,
    isNewOnProvider: true,
    isCurrentlyAiring: true,
    renewalState: "airing_now",
    renewalBadgeText: "Now Playing in Theaters",
    renewalNewsSummary: "Cannes and festival sensation enjoying extended domestic theatrical runs.",
    cast: [
      { name: "Animation Cast", role: "Cat, Capybara, Lemur & Dog" }
    ],
    seasons: [
      {
        seasonNumber: 1,
        title: "Theatrical Run",
        episodeCount: 1,
        releaseDate: "2026-01-16",
        status: "released"
      }
    ]
  }
];
